center/urls.py
try:
    from django.conf.urls import *
except ImportError:  # django < 1.4
    from django.conf.urls.defaults import *

# place app url patterns here

checkin/urls.py
from django.urls import re_path
from . import control
from . import views
from . import dashboard

app_name = 'checkin'
urlpatterns = [

    re_path(r'^qrcheckin/(\d+)$', views.checkin, name='qrcheckin'),
    re_path(r'^ck/([^/]+)$', control.ck, name='qrck'),
    re_path(r'^ajax/getqrstr/(\d+)$', control.getqrstr, name='getqrstr'),
    re_path(r'^ajax/getcheckinnowdata/(\d+)$', control.getcheckinnowdata, name='getcheckinnowdata'),
    re_path(r'^ajax/changecheckinstatus/(\d+)$', control.changecheckinstatus, name='changecheckinstatus'),
    re_path(r'^get_position$', control.get_position, name='get_position'),
    re_path(r'^control/startcheckin/(\d+)$', control.startCheckin, name='startcheckin'),
    re_path(r'^control/stopcheckin/(\d+)$', control.stopCheckin, name='stopcheckin'),
    re_path(r'^control/clearcheckin/(\d+)$', control.clearcheckin, name='clearcheckin'),
    re_path(r'^control/switch_to_add/(\d+)$', control.switch_to_add, name='switch_to_add'),

    re_path(r'^data/student_data/([^/]*)$', views.student_data, name='student_data'),
    re_path(r'^data/teacher_data/([^/]*)$', views.teacher_data, name='teacher_data'),
    re_path(r'^data/class_data/([^/]*)$', views.class_data, name='class_data'),
    re_path(r'^data/personal_data$', views.personaldata, name='personal_data'),
    re_path(r'^data/lesson_data/(\d+)$', views.lesson_data, name='lesson_data'),

    re_path(r'^askmanager$', views.askmanager, name='askmanager'),
    re_path(r'^ajax/getaskdata$', views.askdata, name='getaskdata'),
    re_path(r'^ajax/addask$', control.addask, name='addask'),
    re_path(r'^ajax/delask$', control.delask, name='delask'),

    re_path(r'^jumptolesson_data/(\d+)', views.jumptolesson_data, name='jumptolesson_data'),

    re_path(r'^dashboard/overview', dashboard.overview, name='dashboard_overview'),
    re_path(r'^dashboard/today$', dashboard.today, name='dashboard_today'),
    re_path(r'^dashboard/today_data', dashboard.today_data, name='dashboard_today_data'),
    re_path(r'^dashboard/week$', dashboard.week, name='dashboard_week'),
    re_path(r'^dashboard/week_data', dashboard.week_data, name='dashboard_week_data'),
    re_path(r'^dashboard/term$', dashboard.term, name='dashboard_term'),
    re_path(r'^dashboard/term_data', dashboard.term_data, name='dashboard_term_data'),
    re_path(r'^dashboard/lesson_data', dashboard.lesson_data, name='dashboard_lesson_data'),
    re_path(r'^dashboard/history', dashboard.history, name='dashboard_history'),

    re_path(r'^checkin_success_test', views.checkin_success_test, name='checkin_success_test'),
    re_path(r'^qrcode$', views.qrcode, name='qrcode'),

]

checkinsystem/urls.py
from django.urls import re_path
from django.conf.urls import include
from django.conf.urls.static import static
from django.conf import settings
from center.views import home

app_name = 'checkinsystem'
urlpatterns = [
    re_path(r'^$', home, name='home'),

    re_path(r'^wechat/', include('wechat.urls', namespace="wechat")),
    re_path(r'^user/', include('user_system.urls', namespace="user")),
    re_path(r'^school/', include('school.urls', namespace="school")),
    re_path(r'^course/', include('course.urls', namespace="course")),
    re_path(r'^checkin/', include('checkin.urls', namespace="checkin")),
    # re_path(r'^seat$', 'center.views.seat', name='seat'),
]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += [
        re_path(r'^__debug__/', include(debug_toolbar.urls)),
    ]
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

course/urls.py
from django.urls import re_path
from . import schedule
from . import views
from . import control
from . import ics

app_name = 'course'
urlpatterns = [

    re_path(r'^schedule$', schedule.schedule, name='schedule'),
    re_path(r'^ajax/schedule_data$', schedule.schedule_data, name='schedule_data'),
    re_path(r'^list$', views.list, name='list'),
    re_path(r'^studentcourse/(\d+)$', views.studentcourse, name='studentcourse'),
    re_path(r'^ajax/data$', views.data, name='course_data'),
    re_path(r'^information/(\d+)$', views.information, name='information'),
    re_path(r'^control/startlesson/$', control.startLesson, name='control.startlesson'),
    re_path(r'^control/stoplesson/$', control.stopLesson, name='control.stoplesson'),
    re_path(r'^control/clearlesson/$', control.clearLesson, name='control.clearlesson'),
    re_path(r'^control/sethomeworkscore/$', control.sethomeworkscore, name='control.sethomeworkscore'),
    re_path(r'^control/leavehomeworkcomment/$', control.leavehomeworkcomment, name='control.leavehomeworkcomment'),
    re_path(r'^control/setperformance_score/(\d+)$', control.setperformance_score, name='control.setperformance_score'),
    re_path(r'^control/remind_homework/(\d+)$', control.remind_homework, name='control.remind_homework'),
    re_path(r'^resource/(\d+)$', views.resource, name='resource'),
    re_path(r'^resource/upload$', views.resourceupload, name='resourceupload'),
    re_path(r'^resource/delete$', views.resourcedelete, name='resourcedelete'),
    re_path(r'^course_data/(\d+)$', views.course_data, name='course_data'),
    re_path(r'^homework/(\d+)$', views.homework, name='homework'),
    re_path(r'^homework_commit/(\d+)$', views.get_homework_commit, name='get_homework_commit'),
    re_path(r'^sendmessage/(\d+)$', views.sendmessage, name='sendmessage'),
    re_path(r'^settings/(\d+)', views.settings, name='settings'),

    re_path(r'^codeview', views.codeview, name='codeview'),
    re_path(r'^imgview', views.imgview, name='imgview'),
    re_path(r'^studentcourse_selectdata/(\d+)$', views.studentcourse_selectdata, name='studentcourse_selectdata'),

    re_path(r'^ics/(\d+).ics$', ics.ics, name='ics'),
    re_path(r'^ics/download$', ics.download, name='ics_download'),
    re_path(r'^office_preview$', views.office_preview, name='office_preview'),

    re_path(r'^student_exam/([^/]*)$', views.student_exam, name='student_exam'),
    re_path(r'^personalexam$', views.personalexam, name='personal_exam'),
    re_path(r'^history$', views.course_history, name='course_history'),

]

course/views.py
# -*- coding: utf-8 -*-
import json

from django.db.models import Q, Subquery, OuterRef
from django.http import HttpResponse
from urllib.parse import unquote
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse
from course.auth import has_course_permission, is_course_student
from .models import Course, Lesson, Studentcourse, Courseresource, Coursehomework, Homeworkfile, Homeworkcommit, \
    CourseMessage, StudentExam
from school.models import Student, Teacher
from checkin.models import Scoreregulation, Checkin
from django.db.models import ObjectDoesNotExist
from .constant import *
from user_system.auth import permission_required
from school.function import getCurrentSchoolYearTerm
import time
from .message import sendmessagetocoursestudent
from course.tasks import send_homework_notification, send_resource_notification
from urllib.parse import quote
from checkin.constant import *
from django.core.exceptions import ValidationError


def information(request, courseid):
    coursedata = Course.objects.get(id=courseid)
    lessondata = Lesson.objects.filter(course=coursedata) \
        .exclude(status=LESSON_STATUS_TRANSFERRED) \
        .order_by('week', 'day', 'time').all()
    return render(request, 'information.html',
                  {'coursedata': coursedata, 'lessondata': lessondata,
                   'courseperms': has_course_permission(request.user, coursedata)})


@permission_required(permission='course_viewlist')
def list(request):
    return render(request, 'list.html', {'term': getCurrentSchoolYearTerm()})


@permission_required(permission='course_viewlist')
def data(request):
    order = request.GET['order']
    limit = int(request.GET['limit'])
    offset = int(request.GET['offset'])
    # lessondata = Lesson.objects.all()[offset: (offset + limit)]
    sort = request.GET.get('sort', '')
    if not sort == '':
        if order == "asc":
            coursedata = Course.objects.order_by(sort)
        else:
            coursedata = Course.objects.order_by("-%s" % sort)
    else:
        coursedata = Course.objects
    schoolterm = request.GET.get('schoolterm', default=None)
    if schoolterm:
        coursedata = coursedata.filter(schoolterm=schoolterm)
    major = request.GET.get('major', '')
    if not major == '':
        if major[:1] == '*':
            coursedata = coursedata.filter(department__name=major[1:])
        else:
            coursedata = coursedata.filter(major__name=major)
    search = request.GET.get('search', '')
    if not search == '':
        count = coursedata.filter(
            (Q(title__icontains=search) | Q(teachers__name__icontains=search)) | Q(serialnumber=search)
        ).count()
        coursedata = coursedata.prefetch_related('teachers').select_related('major').select_related(
            'department').filter(
            (Q(title__icontains=search) | Q(teachers__name__icontains=search)) | Q(serialnumber=search)
        )[offset: (offset + limit)]
    else:
        count = coursedata.count()
        coursedata = coursedata.select_related('major').select_related(
            'department').all()[offset: (offset + limit)]

    rows = []
    for p in coursedata:
        ld = {'id': p.id, 'serialnumber': p.serialnumber, 'title': p.title, 'number': p.number,
              'schoolterm': p.schoolterm, 'time': p.time, 'location': p.location,
              'teacher': ",".join(p.teachers.values_list('name', flat=True)),
              'major': (p.major and [p.major.name] or [None])[0],
              'department': (p.department and [p.department.name] or [None])[0]}
        rows.append(ld)
    data = {'total': count, 'rows': rows}
    return HttpResponse(json.dumps(data), content_type="application/json")


def studentcourse(request, courseid):
    coursedata = Course.objects.get(id=courseid)
    students = Studentcourse.objects.filter(course=coursedata). \
        select_related('student', 'student__classid', 'student__classid__major', 'student__classid__department') \
        .order_by('student_id').all()
    return render(request, 'studentcourse.html',
                  {'coursedata': coursedata, 'students': students,
                   'courseperms': has_course_permission(request.user, coursedata)})


def resource(request, courseid):
    coursedata = Course.objects.get(id=courseid)
    resources = Courseresource.objects.filter(course=coursedata).all()
    resources.order_by('uploadtime')
    return render(request, 'resource.html',
                  {'coursedata': coursedata, 'courseperms': has_course_permission(request.user, coursedata),
                   'resources': resources})


def sendmessage(request, courseid):
    coursedata = Course.objects.get(id=courseid)
    messages = CourseMessage.objects.filter(course=coursedata).order_by('-time').all()
    data = {'coursedata': coursedata, 'courseperms': has_course_permission(request.user, coursedata),
            'messages': messages}
    if request.META['REQUEST_METHOD'] == 'POST':
        message = request.POST.get('message')
        errorsendstudentnames = sendmessagetocoursestudent(coursedata, message)
        data['send'] = True
        data['errorsendstudentnames'] = errorsendstudentnames
    return render(request, 'sendmessage.html', data)


def resourceupload(request):
    coursedata = Course.objects.get(id=request.POST.get('courseid'))
    if not has_course_permission(request.user, coursedata):
        return HttpResponse(json.dumps({'error': u'没有权限上传到此课程'}), content_type="application/json")
    res = Courseresource(course=coursedata, uploadtime=time.strftime('%Y-%m-%d %H:%M:%S', time.localtime()))
    res.file = request.FILES['file_data']
    res.title = res.file.name
    res.save()
    send_resource_notification.delay(res.id)
    deleteurl = reverse('course:resourcedelete', args=[])
    initialpreviewdata = res.initialPreview()
    data = {
        'initialPreview': [initialpreviewdata['data']],
        'initialPreviewConfig': [
            {
                'caption': res.title,
                'url': deleteurl,
                'key': res.id
            },
        ]
    }
    if 'type' in initialpreviewdata:
        data['initialPreviewConfig'][0]['type'] = initialpreviewdata['type']
    if 'filetype' in initialpreviewdata:
        data['initialPreviewConfig'][0]['filetype'] = initialpreviewdata['filetype']
    return HttpResponse(json.dumps(data), content_type="application/json")


def resourcedelete(request):
    key = request.POST.get('key')
    res = Courseresource.objects.get(id=key)
    if not has_course_permission(request.user, res.course):
        return HttpResponse(json.dumps({'error': u'没有权限删除此课程文件'}), content_type="application/json")
    res.file.delete()
    res.delete()
    return HttpResponse(json.dumps([]), content_type="application/json")


def homework(request, courseid):
    coursedata = Course.objects.get(id=courseid)
    courseperms = has_course_permission(request.user, coursedata)
    coursestudent = is_course_student(coursedata, request.user)
    if request.GET.get('newhomework'):
        if request.META['REQUEST_METHOD'] == 'POST':
            if not courseperms:
                return HttpResponse(json.dumps({'error': 101, 'message': '没有权限'}), content_type="application/json")
            title = request.POST.get('title')
            deadline = request.POST.get('deadline')
            type = request.POST.get('type')
            if type == 'onlinesubmit':
                type = COURSE_HOMEWORK_TYPE_ONLINESUBMIT
            elif type == 'nosubmit':
                type = COURSE_HOMEWORK_TYPE_NOSUBMIT
            instruction = request.POST.get('instruction')
            attachments = request.FILES.getlist('attachment')
            weight = request.POST.get('weight')
            try:
                homework = Coursehomework.objects.create(title=title, deadline=deadline, type=type, weight=weight,
                                                         course=coursedata)
            except ValidationError:
                return render(request, 'error.html', {'message': '截止日期格式错误'})
            homework.instruction = instruction
            homework.deal_base64img()
            homework.save()
            for file in attachments:
                homework.attachment.add(Homeworkfile.objects.create(file=file, title=file.name))
            send_homework_notification.delay(homework.id)
            return redirect(reverse('course:homework', args=[courseid]) + '?homeworkid=%d' % homework.id)
        else:
            return render(request, 'newhomework.html',
                          {'coursedata': coursedata, 'courseperms': courseperms})
    elif request.GET.get('homeworkid'):
        homeworkdata = get_object_or_404(Coursehomework, pk=request.GET.get('homeworkid'))
        data = {'coursedata': coursedata, 'courseperms': courseperms,
                'homework': homeworkdata, 'coursestudent': coursestudent}
        if request.META['REQUEST_METHOD'] == 'POST' and COURSE_HOMEWORK_TYPE_ONLINESUBMIT == homeworkdata.type:
            if not coursestudent:
                return HttpResponse(json.dumps({'error': 101, 'message': '上课名单里没有你'}), content_type="application/json")
            text = request.POST.get('text')
            attachments = request.FILES.getlist('attachment')
            commitdata, created = Homeworkcommit.objects.get_or_create(student=coursestudent,
                                                                       coursehomework=homeworkdata)
            if commitdata.score:
                pass  # 已经判完分数
            commitdata.text = text
            commitdata.deal_base64img()
            commitdata.submittime = time.strftime('%Y-%m-%d %H:%M:%S', time.localtime())
            if not created and attachments:
                for ca in commitdata.attachment.exclude(title=None).all():
                    ca.file.delete()
                    ca.delete()
            for file in attachments:

course/templates/course_history.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load checkin_extra %}
{% load school_extra %}
{% block title %}历史课程{% endblock %}
{% block page_css %}
    <link href="{% static 'plugins/bootstrap-table/bootstrap-table.min.css' %}" rel="stylesheet">
{% endblock %}
{% block page_js %}
    <script src="{% static 'plugins/bootstrap-table/bootstrap-table.js' %}"></script>
    <script src="{% static 'plugins/bootstrap-table/locale/bootstrap-table-zh-CN.min.js' %}"></script>
{% endblock %}
{% block content %}
    <div class="row">
        <div class="col-sm-12">
            <div class="box box-primary">
                <div class="box-header">
                    <h3 class="box-title">历史课程</h3>
                </div>
                <div class="box-body">
                    <div class="adv-table">
                        <table id="table"
                               data-search="false"
                               data-pagination="false"
                               data-striped="true"
                               data-card-view="true"
                        >
                        </table>


                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}
{% block page_script %}
    <script>
        $.extend($.fn.bootstrapTable.defaults, $.fn.bootstrapTable.locales['zh-CN']);
        var $table = $('#table');

        function titleFormatter(value, row, index) {
            var clickurl = "{% url 'course:information' 0 %}";
            clickurl = clickurl.substring(0, clickurl.length - 1);
            if (row.id === null){
                return value;
            }
            return "<a href='" + clickurl + row.id + "'>" + value + "</a>";
        }

        $table.bootstrapTable({
            formatNoMatches: function () {
                return '没有找到历史课程'
            },
            columns: [
                {
                    field: 'title',
                    title: '课程',
                    formatter: titleFormatter
                }, {
                    field: 'serialnumber',
                    title: '课程编号'
                }, {
                    field: 'schoolterm',
                    title: '学期'
                }
            ],
            data:{{data|safe}}
        });
    </script>
{% endblock %}

course/templates/coursenav.html
{% load center_extra %}
<ul class="nav nav-tabs">
    <li role="presentation" class="{% nav_active request.path 'information' %}">
        <a href="{% url 'course:information' coursedata.id %}">信息</a>
    </li>
    {% if courseperms or perms.checkin_view %}
        <li role="presentation" class="{% nav_active request.path 'lesson_data' %}" id="lesson_tag"
            {% if not coursedata.status %}
            style="display: none;"
            {% endif %}
        >
            <a href="{% url 'checkin:jumptolesson_data' coursedata.id %}">考勤</a>
        </li>
    {% endif %}
    <li role="presentation" class="{% nav_active request.path 'resource' %}">
        <a href="{% url 'course:resource' coursedata.id %}">资源</a>
    </li>
    <li role="presentation" class="{% nav_active request.path 'homework' %}">
        <a href="{% url 'course:homework' coursedata.id %}">作业</a>
    </li>
    {% if courseperms or perms.checkin_view %}
        <li role="presentation" class="{% nav_active request.path 'course_data' %}">
            <a href="{% url 'course:course_data' coursedata.id %}">数据</a>
        </li>
        <li role="presentation" class="{% nav_active request.path 'studentcourse' %}">
            <a href="{% url 'course:studentcourse' coursedata.id %}">学生</a>
        </li>
    {% endif %}
    {% if courseperms %}
        <li role="presentation" class="{% nav_active request.path 'sendmessage' %}">
            <a href="{% url 'course:sendmessage' coursedata.id %}">群发</a>
        </li>
        <li role="presentation" class="{% nav_active request.path 'settings' %}">
            <a href="{% url 'course:settings' coursedata.id %}">设置</a>
        </li>
    {% endif %}
</ul>

course/templates/schedule.html
{% extends 'base.html' %}
{% load static %}
{% load school_extra %}
{% block title %}课表{% endblock %}
{% block page_css %}
    <link href="{% static 'ownplugins/schedule/css/calendar.min.css' %}" rel="stylesheet"/>
    <link rel="stylesheet" href="{% static 'plugins/chosen/chosen1.1.css' %}">
    <style>
        [class^="bg-"] {
            opacity: .65;
            filter: alpha(opacity=65)
        }
    </style>
{% endblock %}
{% block page_js %}
    <script src="{% static 'ownplugins/schedule/underscore/underscore-min.js' %}"></script>
    <script src="{% static 'ownplugins/schedule/js/language/zh-CN.js' %}"></script>
    <script src="{% static 'ownplugins/schedule/js/calendar.min.js' %}"></script>
    <script src="{% static 'plugins/chosen/chosen.jquery.min.js' %}"></script>
{% endblock %}
{% block content %}
    {% if 'iPhone' in request.META.HTTP_USER_AGENT %}
        <div class="callout callout-warning" onclick="window.location.href='{% url 'course:ics_download' %}'">
            <h4>导入课表到日历</h4>
            <p>点击此处、一键导入课表到日历</p>
        </div>
    {% endif %}
    <div class="row">
        <div class="col-sm-12">

            <div class="box box-primary">
                <div class="box-header">
                    <h3 class="box-title">课程表</h3>
                    <select name="viewType2" id="schoolterm" data-placeholder="学年学期">
                        {% getterm as termdata %}

                        {% for m in termdata %}
                            {% gettermdate m as mdate %}
                            <option value="{{ m }}" data-startdate="{{ mdate.0|date:"Y-m-d" }}"
                                    data-enddate="{{ mdate.1|date:"Y-m-d" }}"
                                    {% if m == term %}selected{% endif %}>{{ m }}</option>
                        {% endfor %}
                    </select>
                </div>
                <div class="box-body">
                    <div class="row">
                        <div class="col-sm-4 col-xs-7">
                            <div class="btn-group pull-left">
                                <button class="btn btn-info btn-xs" data-calendar-nav="prev">&lt;&lt; 前</button>
                                <button class="btn btn-info btn-xs" data-calendar-nav="next">后 &gt;&gt;</button>
                                <button class="btn btn-primary btn-xs" data-calendar-nav="today">今天</button>
                            </div>
                        </div>
                        <div class="hidden-xs col-sm-4" style="text-align:center;"><span class="scheduletime"></span>
                        </div>
                        <div class="col-sm-4 col-xs-5">
                            <div class="btn-group pull-right">
                                <button class="btn btn-warning btn-xs active" data-calendar-view="month">月</button>
                                <button class="btn btn-warning btn-xs" data-calendar-view="week">周</button>
                                <button class="btn btn-warning btn-xs" data-calendar-view="day">日</button>
                            </div>
                        </div>
                    </div>
                    <div class="row visible-xs">
                        <div class="col-xs-12" style="text-align:center;">
                            <span class="scheduletime">123</span>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-sm-12">
                            <div id="calendar"></div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- page end-->
{% endblock %}

{% block page_script %}
    <script>
        var term = '{{ term }}';
        var startdate = new Date('{{ startdate|date:"Y-m-d" }}');
        var enddate = new Date('{{ enddate|date:"Y-m-d" }}');
        var now = new Date();
        startdate.setHours(0, 0, 0, 0);
        enddate.setHours(0, 0, 0, 0);
        enddate.setDate(enddate.getDate() + 1)
    </script>
    <script>
        var options = {
            language: 'zh-CN',
            classtime: {{ classtime|safe }},
            weekbetw: startdate,
            first_day: {% if WEEK_FIRST_DAY == 0 %}2{% else %}{{ WEEK_FIRST_DAY }}{% endif %},
            events_source: function (start, end, timezone) {
                var events_data = [];
                if (start < startdate) {
                    start = startdate;
                }
                if (end > enddate) {
                    end = enddate;
                }
                nend = new Date(end);
                nend.setDate(nend.getDate() - 1);
                nstart = start.getFullYear() + '-' + (start.getMonth() + 1) + '-' + start.getDate();
                nend = nend.getFullYear() + '-' + (nend.getMonth() + 1) + '-' + nend.getDate();

                $.ajax({
                    url: '{% url 'course:schedule_data' %}',
                    type: 'GET',
                    dataType: "json",
                    contentType: "application/json; charset=utf-8",
                    data: {
                        start: nstart,
                        end: nend,
                        term: term,
                    },
                    async: false,
                }).done(function (json) {
                    $(json).each(function () {
                        $(this).attr('start', $(this).attr('start') * 1000);
                        $(this).attr('end', $(this).attr('end') * 1000);
                    });
                    events_data = json;
                });
                return events_data;
            },
            view: '{{ view|default:"week" }}',
            tmpl_path: '{% static 'ownplugins/schedule/tmpls' %}/',
            tmpl_cache: false,
            onAfterViewLoad: function (view) {
                $('.scheduletime').text(this.getTitle());
                $('.btn-group button').removeClass('active');
                $('button[data-calendar-view="' + view + '"]').addClass('active');
                viewend = this.options.position.end;
                viewstart = this.options.position.start;
                if (viewend >= enddate) {
                    $('.btn-group button[data-calendar-nav="next"]').attr("disabled", true);
                }
                else {
                    $('.btn-group button[data-calendar-nav="next"]').removeAttr("disabled")
                }
                if (viewstart <= startdate) {
                    $('.btn-group button[data-calendar-nav="prev"]').attr("disabled", true);
                }
                else {
                    $('.btn-group button[data-calendar-nav="prev"]').removeAttr("disabled")
                }
            },
            classes: {
                months: {
                    general: 'label'
                }
            }
        };

        var $calendar = $('#calendar').calendar(options);

        $('.btn-group button[data-calendar-nav]').each(function () {
            var $this = $(this);
            $this.click(function () {
                $calendar.navigate($this.data('calendar-nav'));
            });
        });

        $('.btn-group button[data-calendar-view]').each(function () {
            var $this = $(this);
            $this.click(function () {
                $calendar.view($this.data('calendar-view'));
            });
        });
    </script>
    <script>
        {% if day %}
            $calendar.navigate(new Date('{{ day }}'));
        {% else %}
            if (now > enddate || now < startdate) {
                $calendar.navigate(startdate);
                $('.btn-group button[data-calendar-nav="today"]').hide();
            }
        {% endif %}
        $('#schoolterm').chosen();
        $('#schoolterm').on('change', function (evt, params) {
            var sel = $('#schoolterm option:selected');
            startdate = new Date(sel.attr('data-startdate'));
            enddate = new Date(sel.attr('data-enddate'));
            term = sel.val();
            if (now > enddate || now < startdate) {
                $('.btn-group button[data-calendar-nav="today"]').hide();
                $calendar.navigate(startdate);
            } else {
                $('.btn-group button[data-calendar-nav="today"]').show();
                $calendar.navigate('today');
            }
        });
    </script>
{% endblock %}

course/templates/studentexam.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load checkin_extra %}
{% load school_extra %}
{% block title %}学生考试安排{% endblock %}
{% block page_css %}
    <link href="{% static 'plugins/bootstrap-table/bootstrap-table.min.css' %}" rel="stylesheet">
{% endblock %}
{% block page_js %}
    <script src="{% static 'plugins/bootstrap-table/bootstrap-table.js' %}"></script>
    <script src="{% static 'plugins/bootstrap-table/locale/bootstrap-table-zh-CN.min.js' %}"></script>
{% endblock %}
{% block content %}
    <div class="row">
        <div class="col-sm-12">
            <div class="box box-primary">
                <div class="box-header">
                    <h3 class="box-title">学生考试安排 - {{ student.name }}({{ student.studentid }})</h3>
                </div>
                <div class="box-body">
                    <div class="callout callout-warning">
                        <p>如与教务系统不一致,以教务系统为准</p>
                    </div>
                    <div class="adv-table">
                        <table id="table"
                               data-search="false"
                               data-pagination="false"
                               data-striped="true"
                               data-card-view="true"
                        >
                        </table>


                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}
{% block page_script %}
    <script>
        $.extend($.fn.bootstrapTable.defaults, $.fn.bootstrapTable.locales['zh-CN']);
        var $table = $('#table');

        function titleFormatter(value, row, index) {
            var clickurl = "{% url 'course:information' 0 %}";
            clickurl = clickurl.substring(0, clickurl.length - 1);
            if (row.id === null){
                return value;
            }
            return "<a href='" + clickurl + row.id + "'>" + value + "</a>";
        }

        $table.bootstrapTable({
            formatNoMatches: function () {
                return '没有找到考试安排'
            },
            columns: [
                {
                    field: 'title',
                    title: '课程',
                    formatter: titleFormatter
                }, {
                    field: 'time',
                    title: '时间'
                }, {
                    field: 'location',
                    title: '地点'
                }, {
                    field: 'seat',
                    title: '座位'
                }
            ],
            data:{{data|safe}}
        });
    </script>
{% endblock %}