center/urls.py
try:
    from django.conf.urls import *
except ImportError:  # django < 1.4
    from django.conf.urls.defaults import *

# place app url patterns here

checkin/urls.py
from django.urls import re_path
from . import control
from . import views
from . import dashboard

app_name = 'checkin'
urlpatterns = [

    re_path(r'^qrcheckin/(\d+)$', views.checkin, name='qrcheckin'),
    re_path(r'^ck/([^/]+)$', control.ck, name='qrck'),
    re_path(r'^ajax/getqrstr/(\d+)$', control.getqrstr, name='getqrstr'),
    re_path(r'^ajax/getcheckinnowdata/(\d+)$', control.getcheckinnowdata, name='getcheckinnowdata'),
    re_path(r'^ajax/changecheckinstatus/(\d+)$', control.changecheckinstatus, name='changecheckinstatus'),
    re_path(r'^get_position$', control.get_position, name='get_position'),
    re_path(r'^control/startcheckin/(\d+)$', control.startCheckin, name='startcheckin'),
    re_path(r'^control/stopcheckin/(\d+)$', control.stopCheckin, name='stopcheckin'),
    re_path(r'^control/clearcheckin/(\d+)$', control.clearcheckin, name='clearcheckin'),
    re_path(r'^control/switch_to_add/(\d+)$', control.switch_to_add, name='switch_to_add'),

    re_path(r'^data/student_data/([^/]*)$', views.student_data, name='student_data'),
    re_path(r'^data/teacher_data/([^/]*)$', views.teacher_data, name='teacher_data'),
    re_path(r'^data/class_data/([^/]*)$', views.class_data, name='class_data'),
    re_path(r'^data/personal_data$', views.personaldata, name='personal_data'),
    re_path(r'^data/lesson_data/(\d+)$', views.lesson_data, name='lesson_data'),

    re_path(r'^askmanager$', views.askmanager, name='askmanager'),
    re_path(r'^ajax/getaskdata$', views.askdata, name='getaskdata'),
    re_path(r'^ajax/addask$', control.addask, name='addask'),
    re_path(r'^ajax/delask$', control.delask, name='delask'),

    re_path(r'^jumptolesson_data/(\d+)', views.jumptolesson_data, name='jumptolesson_data'),

    re_path(r'^dashboard/overview', dashboard.overview, name='dashboard_overview'),
    re_path(r'^dashboard/today$', dashboard.today, name='dashboard_today'),
    re_path(r'^dashboard/today_data', dashboard.today_data, name='dashboard_today_data'),
    re_path(r'^dashboard/week$', dashboard.week, name='dashboard_week'),
    re_path(r'^dashboard/week_data', dashboard.week_data, name='dashboard_week_data'),
    re_path(r'^dashboard/term$', dashboard.term, name='dashboard_term'),
    re_path(r'^dashboard/term_data', dashboard.term_data, name='dashboard_term_data'),
    re_path(r'^dashboard/lesson_data', dashboard.lesson_data, name='dashboard_lesson_data'),
    re_path(r'^dashboard/history', dashboard.history, name='dashboard_history'),

    re_path(r'^checkin_success_test', views.checkin_success_test, name='checkin_success_test'),
    re_path(r'^qrcode$', views.qrcode, name='qrcode'),

]

checkinsystem/urls.py
from django.urls import re_path
from django.conf.urls import include
from django.conf.urls.static import static
from django.conf import settings
from center.views import home

app_name = 'checkinsystem'
urlpatterns = [
    re_path(r'^$', home, name='home'),

    re_path(r'^wechat/', include('wechat.urls', namespace="wechat")),
    re_path(r'^user/', include('user_system.urls', namespace="user")),
    re_path(r'^school/', include('school.urls', namespace="school")),
    re_path(r'^course/', include('course.urls', namespace="course")),
    re_path(r'^checkin/', include('checkin.urls', namespace="checkin")),
    # re_path(r'^seat$', 'center.views.seat', name='seat'),
]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += [
        re_path(r'^__debug__/', include(debug_toolbar.urls)),
    ]
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

school/urls.py
from django.urls import re_path
from . import student
from . import managementview
from . import teacher

app_name = 'school'
urlpatterns = [

    re_path(r'^studentlist$', student.studentlist, name='studentlist'),
    re_path(r'^ajax/studentdata$', student.data, name='getstudentdata'),
    re_path(r'^ajax/studentselectdata$', student.selectdata, name='getstudentselectdata'),
    re_path(r'^ajax/teacherselectdata$', teacher.selectdata, name='getteacherselectdata'),
    re_path(r'^teacherlist', teacher.teacherlist, name='teacherlist'),
    re_path(r'^ajax/teacherdata$', teacher.data, name='getteacherdata'),
    re_path(r'^classlist', managementview.classlist, name='classlist'),
    re_path(r'^ajax/classdata', managementview.classdata, name='getclassdata'),
    re_path(r'^majorlist', managementview.majorlist, name='majorlist'),
    re_path(r'^ajax/majordata', managementview.majordata, name='getmajordata'),
    re_path(r'^departmentlist', managementview.departmentlist, name='departmentlist'),
    re_path(r'^ajax/departmentdata', managementview.departmentdata, name='getdepartmentdata'),
    re_path(r'^administrationlist', managementview.administrationlist, name='administrationlist'),
    re_path(r'^ajax/administrationdata', managementview.administrationdata, name='getadministrationdata'),
    re_path(r'^classroomlist', managementview.classroomlist, name='classroomlist'),
    re_path(r'^ajax/classroomdata', managementview.classroomdata, name='getclassroomdata'),
    re_path(r'^schoolterm$', managementview.schoolterm, name='schoolterm'),
    re_path(r'^classtime$', managementview.classtime, name='classtime'),

]

school/models.py
# -*- coding: utf-8 -*-
from django.db import models
from django.db.models.signals import post_save, pre_save
from django.dispatch import receiver
from django.core.cache import cache
from django.utils.functional import cached_property
import hashlib


class Administration(models.Model):
    name = models.CharField(max_length=50)

    def __unicode__(self):
        return u"%s" % (self.name)

    @cached_property
    def teachernumber(self):
        return self.teacher_set.count()

    class Meta:
        db_table = 'Administration'


class Class(models.Model):
    department = models.ForeignKey('Department', models.SET_NULL, db_column='departmentid', null=True)
    schoolyear = models.SmallIntegerField(null=True)
    major = models.ForeignKey('Major', models.SET_NULL, db_column='majorid', null=True)
    name = models.CharField(max_length=255)
    wechatdepartmentid = models.SmallIntegerField(null=True)

    def __unicode__(self):
        return u"%s" % (self.name)

    class Meta:
        db_table = 'Class'


class Classtime(models.Model):
    id = models.IntegerField(primary_key=True)
    starttime = models.TimeField(blank=True, null=True)
    endtime = models.TimeField(blank=True, null=True)

    class Meta:
        db_table = 'ClassTime'


@receiver(post_save, sender=Classtime)
def classtime_post_save(sender, **kwargs):
    cache.delete('classtimedata')


class Classroom(models.Model):
    location = models.CharField(max_length=50)
    seattype = models.ForeignKey('Seat', models.SET_NULL, db_column='seattype', null=True)

    def __unicode__(self):
        return u"%s" % (self.location)

    class Meta:
        db_table = 'Classroom'


class Department(models.Model):
    name = models.CharField(max_length=50)
    wechatdepartmentid = models.SmallIntegerField(null=True)

    @cached_property
    def majoramount(self):
        return self.major_set.count()

    @cached_property
    def studentnumber(self):
        return self.student_set.count()

    @cached_property
    def teachernumber(self):
        return self.teacher_set.count()

    def __unicode__(self):
        return u"%s" % (self.name)

    class Meta:
        db_table = 'Department'


class Major(models.Model):
    department = models.ForeignKey(Department, models.SET_NULL, db_column='departmentid', null=True)
    name = models.CharField(max_length=50)

    def __unicode__(self):
        return u"%s" % (self.name)

    @cached_property
    def studentnumber(self):
        return self.student_set.count()

    @cached_property
    def classamount(self):
        return self.class_set.count()

    class Meta:
        db_table = 'Major'


class Schoolterm(models.Model):
    schoolyear = models.IntegerField()
    description = models.CharField(max_length=20)
    now = models.BooleanField(null=True)
    startdate = models.DateField()
    enddate = models.DateField()

    def __unicode__(self):
        return u"%s" % (self.description)

    class Meta:
        db_table = 'SchoolTerm'


@receiver(post_save, sender=Schoolterm)
def schoolterm_post_save(sender, **kwargs):
    cache.delete_many(['currentschoolyearterm', 'termdata', 'schoolyeardata'])


class Seat(models.Model):
    seattype = models.AutoField(primary_key=True)
    maxnumber = models.SmallIntegerField(null=True)
    mapid = models.IntegerField(null=True)

    def __unicode__(self):
        return "%d" % self.seattype

    class Meta:
        db_table = 'Seat'


class Student(models.Model):
    studentid = models.CharField(primary_key=True, max_length=11)
    idnumber = models.CharField(max_length=18, null=True)
    name = models.CharField(max_length=20)
    sex = models.SmallIntegerField(null=True)

    classid = models.ForeignKey(Class, models.SET_NULL, db_column='classid', null=True)  # can't name to class

    department = models.ForeignKey(Department, models.SET_NULL, db_column='departmentid', null=True)
    major = models.ForeignKey(Major, models.SET_NULL, db_column='majorid', null=True)
    user = models.ForeignKey('user_system.User', models.PROTECT, db_column='userid', null=True)
    available = models.BooleanField(default=True)

    def generateuser(self, save=True):
        if self.user is None and self.idnumber is not None:
            from user_system.models import User, Role, Usertorole
            studentrole = Role.objects.get(name=u'学生')
            m = hashlib.md5()
            m.update(self.idnumber)
            password = m.hexdigest()
            self.user = User.objects.create(academiccode=self.studentid, password=password, sex=self.sex,
                                            mainrole=u'学生')
            Usertorole.objects.create(user=self.user, role=studentrole)
            if save:
                self.save()
        return self.user

    def __unicode__(self):
        return u"%s" % (self.name)

    class Meta:
        db_table = 'Student'


@receiver(pre_save, sender=Student)
def student_pre_save(sender, instance, **kwargs):
    instance.generateuser(save=False)


class Teacher(models.Model):
    teacherid = models.CharField(primary_key=True, max_length=8)
    name = models.CharField(max_length=20)
    sex = models.SmallIntegerField(null=True)
    idnumber = models.CharField(max_length=18, null=True)
    user = models.ForeignKey('user_system.User', models.PROTECT, db_column='userid', null=True)
    administration = models.ManyToManyField(Administration, through='Teachertoadministration',
                                            through_fields=('teacher', 'administration'))
    department = models.ManyToManyField(Department, through='Teachertodepartment',
                                        through_fields=('teacher', 'department'))
    available = models.BooleanField(default=True)

    def generateuser(self, save=True):
        if self.user is None and self.idnumber is not None:
            from user_system.models import User, Role, Usertorole
            teacherrole = Role.objects.get(name=u'教师')
            m = hashlib.md5()
            m.update(self.idnumber)
            password = m.hexdigest()
            self.user = User.objects.create(academiccode=self.teacherid, password=password, sex=self.sex,
                                            mainrole=u'教师')
            Usertorole.objects.create(user=self.user, role=teacherrole)
            if save:
                self.save()
        return self.user

    def __unicode__(self):
        return u"%s" % (self.name)

    class Meta:
        db_table = 'Teacher'


@receiver(pre_save, sender=Teacher)
def teacher_pre_save(sender, instance, **kwargs):
    instance.generateuser(save=False)


class Teachertoadministration(models.Model):
    teacher = models.ForeignKey(Teacher, models.CASCADE, db_column='teacherid')
    administration = models.ForeignKey(Administration, models.CASCADE, db_column='administrationid')

    class Meta:
        db_table = 'TeachertoAdministration'
        index_together = ["teacher", "administration"]


class Teachertodepartment(models.Model):
    teacher = models.ForeignKey(Teacher, models.CASCADE, db_column='teacherid')
    department = models.ForeignKey(Department, models.CASCADE, db_column='departmentid')

    class Meta:
        db_table = 'TeachertoDepartment'
        unique_together = ["teacher", "department"]

school/views.py
# Create your views here.

school/templates/class.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load school_extra %}
{% block title %}班级{% endblock %}
{% block page_css %}
    <link href="{% static 'plugins/bootstrap-table/bootstrap-table.min.css' %}" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'plugins/chosen/chosen1.1.css' %}">

{% endblock %}
{% block page_js %}
    <script src="{% static 'plugins/bootstrap-table/bootstrap-table.min.js' %}"></script>
    <script src="{% static 'plugins/bootstrap-table/locale/bootstrap-table-zh-CN.min.js' %}"></script>
    <script src="{% static 'plugins/chosen/chosen.jquery.min.js' %}"></script>
    <script src="{% static 'plugins/bootstrap-table/bootstrap-table-contextmenu/dist/bootstrap-table-contextmenu.min.js' %}"></script>
{% endblock %}

{% block content %}

    <div class="row">
        <div class="col-sm-12">
            <div class="box box-primary">
                <div class="box-header">
                    <h3 class="box-title">班级列表</h3>
                </div>
                <div class="box-body">
                    <div class="adv-table">
                        <div id="custom-toolbar">
                            <div class="form-inline" role="form">
                                <div class="form-group">
                                    <select name="major" id="major" data-placeholder="系所专业">
                                        <option value selected></option>
                                        {% getmajor as majordata %}
                                        {% for key, value in  majordata.items %}
                                            <optgroup label="{{ key }}">
                                                <option value="*{{ key }}">全部</option>
                                                {% for m in value %}
                                                    <option value="{{ m }}">{{ m }}</option>
                                                {% endfor %}
                                            </optgroup>
                                        {% endfor %}
                                    </select>
                                </div>
                                <div class="form-group">
                                    <select name="viewType2" id="schoolyear" data-placeholder="入学年份">
                                        <option value selected></option>
                                        {% getschoolyear as schoolyeardata %}

                                        {% for m in schoolyeardata %}
                                            <option value="{{ m }}">{{ m }}</option>
                                        {% endfor %}
                                    </select>
                                </div>
                            </div>
                        </div>
                        <table id="table"
                               data-toggle="table"
                               data-striped="true"
                               data-search="true"
                               data-show-refresh="true"
                               data-show-toggle="true"
                               data-show-columns="true"
                               data-show-export="true"
                               data-minimum-count-columns="2"
                               data-pagination="true"
                               data-id-field="id"
                               data-page-size="10"
                               data-page-list="[5,10, 25, 50, 100, ALL]"
                               data-side-pagination="server"
                               data-url="{% url 'school:getclassdata' %}"
                               data-toolbar="#custom-toolbar"
                               data-query-params="queryParams"
                               data-search-text="{{ request.GET.search }}"
                        ></table>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- page end-->

    <ul id="example2-context-menu" class="dropdown-menu">
        {% if perms.school_student_view %}
            <li data-item="student_list"><a>学生列表</a></li>
        {% endif %}
        {% if perms.checkin_view %}
            <li data-item="checkin_view"><a>查看学生考勤</a></li>
        {% endif %}
    </ul>

{% endblock %}
{% block page_script %}
    <script>
        {% if request.GET.major %}
            $("#major").find("option[value='{{ request.GET.major }}']").attr('selected', true);
        {% elif request.GET.department %}
            $("#major").find("option[value='*{{ request.GET.department }}']").attr('selected', true);
        {% endif %}
        {% if request.GET.schoolyear %}
            $("#schoolyear").find("option[value='{{ request.GET.schoolyear }}']").attr('selected', true);
        {% endif %}
        $.extend($.fn.bootstrapTable.defaults, $.fn.bootstrapTable.locales['zh-CN']);
        var $table = $('#table');
        columns = [{
            field: 'name',
            title: '班级',
            searchable: true
        }, {
            field: 'major',
            title: '专业'
        }, {
            field: 'department',
            title: '系所'
        }, {
            field: 'schoolyear',
            title: '入学学年',
            visible: false,
            sortable: true
        }];
        {% if perms.school_student_view or perms.checkin_view%}
            function operateFormatter(value, row, index) {
                return [
                    '<div class="btn-group btn-group-xs">',
                    '    <button type="button" class="btn btn-default dropdown-toggle example2-button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">',
                    '        <span class="caret"></span>',
                    '        <span class="sr-only">操作</span>',
                    '    </button>',
                    '</div>'
                ].join('');
            }
            columns.push({
                field: 'operate',
                title: '操作',
                align: 'center',
                formatter: operateFormatter
            });
            $table.bootstrapTable({
                columns: columns,
                contextMenu: '#example2-context-menu',
                contextMenuButton: '.example2-button',
                onContextMenuItem: function (row, $el) {
                    if ($el.data("item") == "student_list") {
                        window.open("{% url 'school:studentlist' %}?search=" + row.name);
                    } else if ($el.data("item") == "checkin_view") {
                        window.open("{% url 'checkin:class_data' '' %}" + row.id);
                    }
                }
            });
        {% else %}
            $table.bootstrapTable({
                columns: columns
            });
        {% endif %}

        function queryParams(params) {
            params['schoolyear'] = $('#schoolyear').val();
            params['major'] = $('#major').val();
            return params;
        }

        $('#major').chosen({allow_single_deselect: true, include_group_label_in_selected: true});
        $('#schoolyear').chosen({allow_single_deselect: true, width: 60});

        $('#schoolyear').on('change', function (evt, params) {
            $table.bootstrapTable('refresh');
        });
        $('#major').on('change', function (evt, params) {
            $table.bootstrapTable('refresh');
        });
    </script>
{% endblock %}

school/templates/student_list.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load center_extra %}
{% load school_extra %}
{% block title %}学生列表{% endblock %}
{% block page_css %}
    <link href="{% static 'plugins/bootstrap-table/bootstrap-table.min.css' %}" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'plugins/chosen/chosen1.1.css' %}">
    <link href="{% static 'plugins/toastr-master/toastr.css' %}" rel="stylesheet" type="text/css"/>
{% endblock %}
{% block page_js %}
    <script src="{% static 'plugins/bootstrap-table/bootstrap-table.min.js' %}"></script>
    <script src="{% static 'plugins/bootstrap-table/locale/bootstrap-table-zh-CN.min.js' %}"></script>
    <script src="{% static 'plugins/chosen/chosen.jquery.min.js' %}"></script>
    <script src="{% static 'plugins/bootstrap-table/bootstrap-table-contextmenu/dist/bootstrap-table-contextmenu.min.js' %}"></script>
    <script src="{% static 'plugins/toastr-master/toastr.js' %}"></script>
{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-sm-12">
            <div class="box box-primary">
                <div class="box-header">
                    <h3 class="box-title">学生列表</h3>
                </div>
                <div class="box-body">
                    <div class="adv-table">
                        <div id="custom-toolbar">
                            <div class="form-inline" role="form">
                                <div class="form-group">
                                    <select name="major" id="major" data-placeholder="系所专业">
                                        <option value selected></option>
                                        {% getmajor as majordata %}
                                        {% for key, value in  majordata.items %}
                                            <optgroup label="{{ key }}">
                                                <option value="*{{ key }}">全部</option>
                                                {% for m in value %}
                                                    <option value="{{ m }}">{{ m }}</option>
                                                {% endfor %}
                                            </optgroup>
                                        {% endfor %}
                                    </select>
                                </div>
                                <div class="form-group">
                                    <select name="viewType2" id="schoolyear" data-placeholder="入学年份">
                                        <option value selected></option>
                                        {% getschoolyear as schoolyeardata %}

                                        {% for m in schoolyeardata %}
                                            <option value="{{ m }}">{{ m }}</option>
                                        {% endfor %}
                                    </select>
                                </div>
                                {% comment %}
                                <div class="checkbox">
                                    <label>
                                        <input type="checkbox"> 我的课程
                                    </label>
                                </div>
                                <!--<button type="submit" class="btn btn-default">高级搜索</button>-->
                            {% endcomment %}
                            </div>
                        </div>
                        <table id="table"
                               data-toggle="table"
                               data-search="true"
                               data-show-refresh="true"
                               data-show-toggle="true"
                               data-show-columns="true"
                               data-show-export="true"
                               data-minimum-count-columns="2"
                               data-pagination="true"
                               data-id-field="studentid"
                               data-page-size="10"
                               data-page-list="[5,10, 25, 50, 100, ALL]"
                               data-side-pagination="server"
                               data-url="{% url 'school:getstudentdata' %}"
                               data-toolbar="#custom-toolbar"
                               data-striped="true"
                               data-query-params="queryParams"
                               data-search-text="{{ request.GET.search }}"
                        >

                        </table>

                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- page end-->

    <ul id="example2-context-menu" class="dropdown-menu">
        {% if perms.school_student_modify %}
            <li data-item="resetpassword"><a>重置密码</a></li>
        {% endif %}
        {% if perms.checkin_view %}
            <li data-item="checkin_view"><a>查看出勤情况</a></li>
        {% endif %}
    </ul>


{% endblock %}
{% block page_script %}
    <script>
        toastr.options = {
            "closeButton": false,
            "debug": false,
            "progressBar": false,
            "positionClass": "toast-top-center",
            "onclick": null,
            "showDuration": "300",
            "hideDuration": "1000",
            "timeOut": "5000",
            "extendedTimeOut": "1000",
            "showEasing": "swing",
            "hideEasing": "linear",
            "showMethod": "fadeIn",
            "hideMethod": "fadeOut"
        };
        {% if request.GET.major %}
            $("#major").find("option[value='{{ request.GET.major }}']").attr('selected', true);
        {% elif request.GET.department %}
            $("#major").find("option[value='*{{ request.GET.department }}']").attr('selected', true);
        {% endif %}
        {% if request.GET.schoolyear %}
            $("#schoolyear").find("option[value='{{ request.GET.schoolyear }}']").attr('selected', true);
        {% endif %}

        $.extend($.fn.bootstrapTable.defaults, $.fn.bootstrapTable.locales['zh-CN']);
        var $table = $('#table');
        columns = [{
            field: 'name',
            title: '姓名',
            searchable: true
        }, {
            field: 'studentid',
            title: '学号',
            sortable: true,
            order: 'desc'
        }, {
            field: 'sex',
            title: '性别'
        }, {
            field: 'idnumber',
            title: '身份证',
            visible: false
        }, {
            field: 'class',
            title: '班级'
        }, {
            field: 'major',
            title: '专业'
        }, {
            field: 'department',
            title: '系所'
        }, {
            field: 'username',
            title: '用户名',
            visible: false
        }, {
            field: 'phone',
            title: '手机号',
            visible: false
        }, {
            field: 'email',
            title: 'Email',
            visible: false
        }, {
            field: 'schoolyear',
            title: '入学学年',
            visible: false
        }, {
            field: 'ip',
            title: 'ip',
            visible: false
        }, {
            field: 'lastlogintime',
            title: '上次登录',
            visible: false
        }, {
            field: 'iswechat',
            title: '微信关注'
        }];
        {% if perms.school_student_modify or perms.checkin_view%}
            function operateFormatter(value, row, index) {
                return [
                    '<div class="btn-group btn-group-xs">',
                    '    <button type="button" class="btn btn-default dropdown-toggle example2-button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">',
                    '        <span class="caret"></span>',
                    '        <span class="sr-only">操作</span>',
                    '    </button>',
                    '</div>'
                ].join('');
            }
            columns.push({
                field: 'operate',
                title: '操作',
                align: 'center',
                formatter: operateFormatter
            });
            $table.bootstrapTable({
                columns: columns,
                contextMenu: '#example2-context-menu',
                contextMenuButton: '.example2-button',
                onContextMenuItem: function (row, $el) {
                    if ($el.data("item") == "resetpassword") {
                        $.ajax({
                            url: '{% url 'user:control.resetpassword' %}',
                            type: 'GET',
                            dataType: "json",
                            contentType: "application/json; charset=utf-8",
                            data: {
                                userid: row.user_id
                            },
                            success: function (data) {
                                if (data.error != 0) {
                                    toastr['error'](data.message, "操作失败");
                                } else {
                                    toastr['success'](data.message, "操作成功");
                                }
                            }, error: function (XMLHttpRequest, textStatus) {
                                toastr['error'](textStatus, "与服务器连接失败");
                            }
                        });
                    } else if ($el.data("item") == "checkin_view") {
                        window.open("{% url 'checkin:student_data' '' %}" + row.studentid);
                    }
                }
            });
        {% else %}
            $table.bootstrapTable({
                columns: columns
            });
        {% endif %}

        function queryParams(params) {
            params['schoolyear'] = $('#schoolyear').val();
            params['major'] = $('#major').val();
            return params;
        }

        $('#major').chosen({allow_single_deselect: true, include_group_label_in_selected: true});
        $('#schoolyear').chosen({allow_single_deselect: true, width: 60});

        $('#schoolyear').on('change', function (evt, params) {
            $table.bootstrapTable('refresh');
        });
        $('#major').on('change', function (evt, params) {
            $table.bootstrapTable('refresh');
        });


    </script>
{% endblock %}