center/urls.py
try:
    from django.conf.urls import *
except ImportError:  # django < 1.4
    from django.conf.urls.defaults import *

# place app url patterns here

checkin/urls.py
from django.urls import re_path
from . import control
from . import views
from . import dashboard

app_name = 'checkin'
urlpatterns = [

    re_path(r'^qrcheckin/(\d+)$', views.checkin, name='qrcheckin'),
    re_path(r'^ck/([^/]+)$', control.ck, name='qrck'),
    re_path(r'^ajax/getqrstr/(\d+)$', control.getqrstr, name='getqrstr'),
    re_path(r'^ajax/getcheckinnowdata/(\d+)$', control.getcheckinnowdata, name='getcheckinnowdata'),
    re_path(r'^ajax/changecheckinstatus/(\d+)$', control.changecheckinstatus, name='changecheckinstatus'),
    re_path(r'^get_position$', control.get_position, name='get_position'),
    re_path(r'^control/startcheckin/(\d+)$', control.startCheckin, name='startcheckin'),
    re_path(r'^control/stopcheckin/(\d+)$', control.stopCheckin, name='stopcheckin'),
    re_path(r'^control/clearcheckin/(\d+)$', control.clearcheckin, name='clearcheckin'),
    re_path(r'^control/switch_to_add/(\d+)$', control.switch_to_add, name='switch_to_add'),

    re_path(r'^data/student_data/([^/]*)$', views.student_data, name='student_data'),
    re_path(r'^data/teacher_data/([^/]*)$', views.teacher_data, name='teacher_data'),
    re_path(r'^data/class_data/([^/]*)$', views.class_data, name='class_data'),
    re_path(r'^data/personal_data$', views.personaldata, name='personal_data'),
    re_path(r'^data/lesson_data/(\d+)$', views.lesson_data, name='lesson_data'),

    re_path(r'^askmanager$', views.askmanager, name='askmanager'),
    re_path(r'^ajax/getaskdata$', views.askdata, name='getaskdata'),
    re_path(r'^ajax/addask$', control.addask, name='addask'),
    re_path(r'^ajax/delask$', control.delask, name='delask'),

    re_path(r'^jumptolesson_data/(\d+)', views.jumptolesson_data, name='jumptolesson_data'),

    re_path(r'^dashboard/overview', dashboard.overview, name='dashboard_overview'),
    re_path(r'^dashboard/today$', dashboard.today, name='dashboard_today'),
    re_path(r'^dashboard/today_data', dashboard.today_data, name='dashboard_today_data'),
    re_path(r'^dashboard/week$', dashboard.week, name='dashboard_week'),
    re_path(r'^dashboard/week_data', dashboard.week_data, name='dashboard_week_data'),
    re_path(r'^dashboard/term$', dashboard.term, name='dashboard_term'),
    re_path(r'^dashboard/term_data', dashboard.term_data, name='dashboard_term_data'),
    re_path(r'^dashboard/lesson_data', dashboard.lesson_data, name='dashboard_lesson_data'),
    re_path(r'^dashboard/history', dashboard.history, name='dashboard_history'),

    re_path(r'^checkin_success_test', views.checkin_success_test, name='checkin_success_test'),
    re_path(r'^qrcode$', views.qrcode, name='qrcode'),

]

checkinsystem/urls.py
from django.urls import re_path
from django.conf.urls import include
from django.conf.urls.static import static
from django.conf import settings
from center.views import home

app_name = 'checkinsystem'
urlpatterns = [
    re_path(r'^$', home, name='home'),

    re_path(r'^wechat/', include('wechat.urls', namespace="wechat")),
    re_path(r'^user/', include('user_system.urls', namespace="user")),
    re_path(r'^school/', include('school.urls', namespace="school")),
    re_path(r'^course/', include('course.urls', namespace="course")),
    re_path(r'^checkin/', include('checkin.urls', namespace="checkin")),
    # re_path(r'^seat$', 'center.views.seat', name='seat'),
]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += [
        re_path(r'^__debug__/', include(debug_toolbar.urls)),
    ]
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

course/urls.py
from django.urls import re_path
from . import schedule
from . import views
from . import control
from . import ics

app_name = 'course'
urlpatterns = [

    re_path(r'^schedule$', schedule.schedule, name='schedule'),
    re_path(r'^ajax/schedule_data$', schedule.schedule_data, name='schedule_data'),
    re_path(r'^list$', views.list, name='list'),
    re_path(r'^studentcourse/(\d+)$', views.studentcourse, name='studentcourse'),
    re_path(r'^ajax/data$', views.data, name='course_data'),
    re_path(r'^information/(\d+)$', views.information, name='information'),
    re_path(r'^control/startlesson/$', control.startLesson, name='control.startlesson'),
    re_path(r'^control/stoplesson/$', control.stopLesson, name='control.stoplesson'),
    re_path(r'^control/clearlesson/$', control.clearLesson, name='control.clearlesson'),
    re_path(r'^control/sethomeworkscore/$', control.sethomeworkscore, name='control.sethomeworkscore'),
    re_path(r'^control/leavehomeworkcomment/$', control.leavehomeworkcomment, name='control.leavehomeworkcomment'),
    re_path(r'^control/setperformance_score/(\d+)$', control.setperformance_score, name='control.setperformance_score'),
    re_path(r'^control/remind_homework/(\d+)$', control.remind_homework, name='control.remind_homework'),
    re_path(r'^resource/(\d+)$', views.resource, name='resource'),
    re_path(r'^resource/upload$', views.resourceupload, name='resourceupload'),
    re_path(r'^resource/delete$', views.resourcedelete, name='resourcedelete'),
    re_path(r'^course_data/(\d+)$', views.course_data, name='course_data'),
    re_path(r'^homework/(\d+)$', views.homework, name='homework'),
    re_path(r'^homework_commit/(\d+)$', views.get_homework_commit, name='get_homework_commit'),
    re_path(r'^sendmessage/(\d+)$', views.sendmessage, name='sendmessage'),
    re_path(r'^settings/(\d+)', views.settings, name='settings'),

    re_path(r'^codeview', views.codeview, name='codeview'),
    re_path(r'^imgview', views.imgview, name='imgview'),
    re_path(r'^studentcourse_selectdata/(\d+)$', views.studentcourse_selectdata, name='studentcourse_selectdata'),

    re_path(r'^ics/(\d+).ics$', ics.ics, name='ics'),
    re_path(r'^ics/download$', ics.download, name='ics_download'),
    re_path(r'^office_preview$', views.office_preview, name='office_preview'),

    re_path(r'^student_exam/([^/]*)$', views.student_exam, name='student_exam'),
    re_path(r'^personalexam$', views.personalexam, name='personal_exam'),
    re_path(r'^history$', views.course_history, name='course_history'),

]

school/urls.py
from django.urls import re_path
from . import student
from . import managementview
from . import teacher

app_name = 'school'
urlpatterns = [

    re_path(r'^studentlist$', student.studentlist, name='studentlist'),
    re_path(r'^ajax/studentdata$', student.data, name='getstudentdata'),
    re_path(r'^ajax/studentselectdata$', student.selectdata, name='getstudentselectdata'),
    re_path(r'^ajax/teacherselectdata$', teacher.selectdata, name='getteacherselectdata'),
    re_path(r'^teacherlist', teacher.teacherlist, name='teacherlist'),
    re_path(r'^ajax/teacherdata$', teacher.data, name='getteacherdata'),
    re_path(r'^classlist', managementview.classlist, name='classlist'),
    re_path(r'^ajax/classdata', managementview.classdata, name='getclassdata'),
    re_path(r'^majorlist', managementview.majorlist, name='majorlist'),
    re_path(r'^ajax/majordata', managementview.majordata, name='getmajordata'),
    re_path(r'^departmentlist', managementview.departmentlist, name='departmentlist'),
    re_path(r'^ajax/departmentdata', managementview.departmentdata, name='getdepartmentdata'),
    re_path(r'^administrationlist', managementview.administrationlist, name='administrationlist'),
    re_path(r'^ajax/administrationdata', managementview.administrationdata, name='getadministrationdata'),
    re_path(r'^classroomlist', managementview.classroomlist, name='classroomlist'),
    re_path(r'^ajax/classroomdata', managementview.classroomdata, name='getclassroomdata'),
    re_path(r'^schoolterm$', managementview.schoolterm, name='schoolterm'),
    re_path(r'^classtime$', managementview.classtime, name='classtime'),

]

wechat/urls.py
'''try:
    from django.conf.urls import *
except ImportError:  # django < 1.4
    from django.conf.urls.defaults import *
'''
# place app url patterns here
from django.urls import re_path
from . import api
from . import oauth
from . import views

app_name = 'wechat'
urlpatterns = [
    re_path(r'^api$', api.api, name='api'),
    re_path(r'^wxauth$', views.wxauth, name='wxauth'),
    re_path(r'^wechatlogin$', views.wechatlogin, name='wechatlogin'),
    re_path(r'^toqywechat/([^/]+)$', views.toqywechat, name='toqywechat'),
    re_path(r'^oauth', oauth.oauth, name='oauth'),
]

templates/base-body.html
<!DOCTYPE html>
<html lang="zh-cmn-Hans">
{% include 'head.html' %}
{% block page_css %}

{% endblock %}
<script>document.title = '{% block title %}课程管理系统{% endblock %} - OpenCLMS'</script>
{% block body %}
    <!-- page start-->
    Page content goes here
    <!-- page end-->
{% endblock %}
{% include 'endscript.html' %}
{% block page_js %}

{% endblock %}
{% block page_script %}

{% endblock %}
</html>

templates/base.html
<!DOCTYPE html>
<html lang="zh">
{% include 'head.html' %}
{% block page_css %}
{% endblock %}
<script>document.title = '{% block title %}{% endblock %} - OpenCLMS'</script>
{% if not request.GET.simpleview %}
    <body class="hold-transition skin-blue sidebar-mini sidebar-collapse">
    <div class="wrapper">
    {% include 'header.html' %}
    {% include 'sidebar.html' %}


    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
{% else %}
    <body class="hold-transition skin-blue" style="background-color: #ecf0f5;">
{% endif %}
{% block beforecontent %}{% endblock %}
<!-- Main content -->
<section class="content">
    {% block content %}
        <!-- Your Page Content Here -->
    {% endblock %}
</section>
<!-- /.content -->
{% if not request.GET.simpleview %}
    </div>
    <!-- /.content-wrapper -->


    {% include 'footer.html' %}
    </div>
{% endif %}

{% include 'endscript.html' %}
{% block page_js %}
{% endblock %}
{% block page_script %}
{% endblock %}
</body>
</html>

templates/endscript.html
{% load static %}
<!-- REQUIRED JS SCRIPTS -->
<!-- jQuery 2.2.0 -->
<script src="{% static 'plugins/jQuery/jQuery-2.2.3.min.js' %}"></script>
<!-- Bootstrap 3.3.6 -->
<script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
<!-- PACE -->
<script type="text/javascript">
    window.paceOptions = {ajax: {ignoreURLs: ['piwik']}};
</script>
<script src="{% static 'plugins/pace/pace.min.js' %}"></script>
<!-- AdminLTE App -->
<script src="{% static 'js/adminlte.min.js' %}?2.4.2"></script>
<script>
    if ($(window).width() <= 767) {
        $('body').removeClass("sidebar-collapse");
    }
    $(document).ready(function () {
        $('[data-toggle="tooltip"]').tooltip();
    });
</script>

templates/error.html
{% extends 'base-body.html' %}
{% load static %}
{% block title %}失败{% endblock %}
{% block page_css %}
    <style>
        /*error page*/

        .body-error {
            background: #777;
            color: #fff;
        }

        .error-wrapper .icon-error {
            background: url("{% static 'img/error.png' %}") no-repeat;
            width: 300px;
            height: 300px;
            display: inline-block;
            margin-left: 50px;
        }

        .error-wrapper p.page-error {
            color: #7dfff7;
        }

        .error-wrapper p.page-error a, .error-wrapper p.page-success a, .error-wrapper p.page-error a:hover, .error-wrapper p.page-success a:hover {
            color: #fff;
        }
    </style>
{% endblock %}
{% block body %}
    <body class="body-error">
    <div class="container">
        <section class="error-wrapper notifiy">
            <i class="icon-error"></i>
            <h1 style="font-size: 50px;">{{ message }}</h1>
            <h2>{{ submessage }}</h2>
            <p class="page-error">
                {% if jumpurl %}
                    页面自动 <a id="href" href="{{ jumpurl }}">跳转</a> 等待时间：<b id="wait">{{ waittime|default:3 }}</b>
                {% endif %}
                {% if wechatclose %}
                    页面自动 关闭 等待时间：<b id="wait">{{ waittime|default:3 }}</b>
                {% endif %}
                <a href="{% url 'home' %}">返回主页</a>
            </p>
        </section>
    </div>
    </body>
{% endblock %}
{% block page_script %}
    {% if jumpurl %}
        <script type="text/javascript">
            (function () {
                var wait = document.getElementById('wait'), href = document.getElementById('href').href;
                var interval = setInterval(function () {
                    var time = --wait.innerHTML;
                    if (time <= 0) {
                        location.href = href;
                        clearInterval(interval);
                    }
                    ;
                }, 1000);
            })();
        </script>
    {% endif %}
    {% if wechatclose %}
        <script language="JavaScript" src="http://res.wx.qq.com/open/js/jweixin-1.0.0.js"></script>
        {% load wechat_extra %}
        {% wxconfig request.get_full_path 'closeWindow,hideOptionMenu' as wxc %}
        {{ wxc | safe }}
        <script type="text/javascript">
            wx.ready(function () {
                wx.hideOptionMenu();
                var wait = document.getElementById('wait');
                var interval = setInterval(function () {
                    var time = --wait.innerHTML;
                    if (time <= 0) {
                        wx.closeWindow();
                        clearInterval(interval);
                    }
                    ;
                }, 1000);
            });
        </script>
    {% endif %}
{% endblock %}

templates/footer.html
<!-- Main Footer -->
<footer class="main-footer">
    <!-- To the right -->
    <div class="pull-right hidden-xs">
        {{ SCHOOL_NAME }}
    </div>
    <!-- Default to the left -->
    <strong>Powered by <a href="https://github.com/xiaohuanshu/OpenCLMS">OpenCLMS</a>.</strong>
</footer>

templates/head.html
{% load staticfiles %}
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,Chrome=1"/>
    <meta name="renderer" content="webkit"/>
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <meta name="author" content="yanjing">
    <title>Checkin system</title>


    <!-- Bootstrap 3.3.6 -->
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="{% static 'plugins/font-awesome/css/font-awesome.min.css' %}">
    <!-- Theme style -->
    <link rel="stylesheet" href="{% static 'css/AdminLTE.min.css' %}?2.4.2">
    <!-- AdminLTE Skins. We have chosen the skin-blue for this starter
          page. However, you can choose any other skin. Make sure you
          apply the skin class to the body tag so the changes take effect.
    -->
    <link rel="stylesheet" href="{% static 'css/skins/skin-blue.min.css' %}?2.4.2">
    <!-- Pace style -->
    <link rel="stylesheet" href="{% static 'plugins/pace/pace.min.css' %}">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="{% static 'js/html5shiv.js'%}"></script>
    <script src="{% static 'js/respond.min.js'%}"></script>
    <![endif]-->
</head>

templates/header.html
{% load staticfiles %}
{% load center_extra %}
<!-- Main Header -->
<header class="main-header">

    <!-- Logo -->
    <a href="{% url 'home' %}" class="logo">
        <!-- mini logo for sidebar mini 50x50 pixels -->
        <span class="logo-mini"><b>LM</b>S</span>
        <!-- logo for regular state and mobile devices -->
        <span class="logo-lg"><b>课程管理系统</b></span>
    </a>

    <!-- Header Navbar -->
    <nav class="navbar navbar-static-top">
        <!-- Sidebar toggle button-->
        <a href="#" class="sidebar-toggle" data-toggle="push-menu" role="button">
            <span class="sr-only">Toggle navigation</span>
        </a>
        <!-- Navbar Right Menu -->
        <div class="navbar-custom-menu">
            <ul class="nav navbar-nav">


                <!-- Lesson: style can be found in dropdown.less-->
                <li class="dropdown messages-menu">
                    <!-- Menu toggle button -->
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        <i class="fa fa-book"></i>
                        <span class="label label-success">{{ todaylesson | length }}</span>
                    </a>
                    <ul class="dropdown-menu">
                        <li class="header">你今天有{{ todaylesson | length }}节课</li>
                        {% for lesson in todaylesson %}
                            <li>

                                <ul class="menu">
                                    <li>
                                        <a href="{% url 'course:information' lesson.course.id %}">
                                            <h4>
                                                {{ lesson.course.title }}
                                            </h4>
                                            <p>第{{ lesson.week }}周{{ lesson.day|weekdeal }}
                                                ,第{{ lesson.time }}-{{ lesson.time|add:lesson.length|add:-1 }}节</p>
                                        </a>
                                    </li>
                                </ul>

                            </li>
                        {% endfor %}
                        <li class="footer"><a href="{% url 'course:schedule' %}">查看课表</a></li>
                    </ul>
                </li>
                <!-- /.lesson-menu -->


                <!-- User Account Menu -->
                <li class="dropdown user user-menu">
                    <!-- Menu Toggle Button -->
                    {% if request.user.username %}
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        <!-- The user image in the navbar-->
                        <img src="{{ request.user.avatar.url }}" class="user-image" alt="User Image">
                        <!-- hidden-xs hides the username on small devices so only the image appears. -->
                        <span class="hidden-xs">{{ request.user.username }}</span>
                    </a>
                    <ul class="dropdown-menu">
                        <!-- The user image in the menu -->
                        <li class="user-header">
                            <img src="{{ request.user.avatar.url }}" class="img-circle" alt="User Image">

                            <p>
                                {{ request.user.username }}
                                <small>{{ request.user.email }}</small>
                            </p>
                        </li>
                        <!-- Menu Body -->
                        <li class="user-body">
                            <div class="row">
                                <div class="col-xs-4 text-center">
                                    <a href="{% url 'course:schedule' %}">课表</a>
                                </div>
                                <div class="col-xs-4 text-center">
                                    <a href="{% url 'user:changepassword' %}">设置</a>
                                </div>
                                <div class="col-xs-4 text-center">
                                    <a href="#">提醒</a>
                                </div>
                            </div>
                            <!-- /.row -->
                        </li>
                        <!-- Menu Footer-->
                        <li class="user-footer">
                            <div class="pull-left">
                                <a href="#" class="btn btn-default btn-flat">主页</a>
                            </div>
                            <div class="pull-right">
                                <a href="{% url 'user:logout' %}" class="btn btn-default btn-flat">注销</a>
                            </div>
                        </li>
                    </ul>
                    {% else %}
                        <a href="{% url 'user:register' %}">
                        <img src="{{ request.user.avatar.url }}" class="user-image" alt="User Image">
                        <span>请注册</span>
                    </a>
                    {% endif %}
                </li>
            </ul>
        </div>
    </nav>
</header>

templates/openinbrowser.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Checkin System</title>
</head>
<body style="text-align: center">
<h1 style="margin-top: 300px;">点击右上角，在浏览器(safari)中打开</h1>
</body>
</html>

templates/sidebar.html
{% load center_extra %}
<!-- Left side column. contains the logo and sidebar -->
<aside class="main-sidebar">
    <!-- sidebar: style can be found in sidebar.less -->
    <section class="sidebar">
        <!-- Sidebar Menu -->
        <ul class="sidebar-menu" data-widget="tree">
            <li class="{% nav_active request.path 'home' %}">
                <a href="{% url 'home' %}">
                    <i class="fa fa-home"></i><span>首页</span>
                </a>
            </li>
            <li class="treeview {% nav_menu_active request.path 'course' %}">
                <a href="#"><i class="fa fa-book"></i><span>课程</span>
                    <i class="fa fa-angle-left pull-right"></i></a>
                <ul class="treeview-menu">
                    {% if perms.course_viewlist %}
                        <li class="{% nav_active request.path 'list' %}">
                            <a href="{% url 'course:list' %}"><i class="fa fa-circle-o"></i>全校课程</a>
                        </li>
                    {% endif %}
                    <li class="{% nav_active request.path 'schedule' %}">
                        <a href="{% url 'course:schedule' %}"><i class="fa fa-circle-o"></i>个人课表</a></li>
                    <li class="{% nav_active request.path 'history' %}">
                        <a href="{% url 'course:course_history' %}"><i class="fa fa-circle-o"></i>历史课程</a></li>
                    {% if request.user.isstudent %}
                        <li class="{% nav_active request.path 'personal_exam' %}">
                            <a href="{% url 'course:personal_exam' %}"><i class="fa fa-circle-o"></i>考试安排</a></li>
                    {% endif %}
                </ul>
            </li>
            {% if perms.checkin %}
                <li class="treeview {% nav_menu_active request.path 'checkin' %}">
                    <a href="#"><i class="fa fa-calendar-check-o"></i><span>考勤</span>
                        <i class="fa fa-angle-left pull-right"></i></a>
                    <ul class="treeview-menu">
                        <li class="{% nav_active request.path 'dashboard' %}">
                            <a href="{% url 'checkin:dashboard_overview' %}"><i class="fa fa-circle-o"></i>全校总览</a>
                        </li>
                        <li class="{% nav_active request.path 'personal_data' %}">
                            <a href="{% url 'checkin:personal_data' %}"><i class="fa fa-circle-o"></i>个人数据</a></li>
                        {% if perms.checkin_ask %}
                            <li class="{% nav_active request.path 'askmanager' %}">
                                <a href="{% url 'checkin:askmanager' %}"><i class="fa fa-circle-o"></i>请假管理</a>
                            </li>
                        {% endif %}
                    </ul>
                </li>
            {% endif %}
            {% if perms.wechat %}
                <li class="treeview {% nav_menu_active request.path 'wechat' %}">
                    <a href="#"><i class="fa fa-wechat"></i> <span>微信平台</span>
                        <i class="fa fa-angle-left pull-right"></i></a>
                    <ul class="treeview-menu">
                        <li class=""><a href="{% url 'wechat:toqywechat' 'send_msg' %}" target="_blank">
                            <i class="fa fa-circle-o"></i>信息发送</a></li>
                        <li class=""><a href="{% url 'wechat:toqywechat' 'contact' %}" target="_blank">
                            <i class="fa fa-circle-o"></i>通讯录</a></li>
                    </ul>
                </li>
            {% endif %}
            {% if perms.school %}
                <li class="treeview {% nav_menu_active request.path 'school' %}">
                    <a href="#"><i class="fa fa-building"></i> <span>学校</span>
                        <i class="fa fa-angle-left pull-right"></i></a>
                    <ul class="treeview-menu">
                        {% if perms.school_student_view %}
                            <li class="{% nav_active request.path 'studentlist' %}">
                                <a href="{% url 'school:studentlist' %}"><i class="fa fa-circle-o"></i>学生</a></li>
                        {% endif %}
                        {% if perms.school_teacher_view %}
                            <li class="{% nav_active request.path 'teacherlist' %}">
                                <a href="{% url 'school:teacherlist' %}"><i class="fa fa-circle-o"></i>教师</a></li>
                        {% endif %}
                        {% if perms.school_class_view %}
                            <li class="{% nav_active request.path 'classlist' %}">
                                <a href="{% url 'school:classlist' %}"><i class="fa fa-circle-o"></i>班级</a></li>
                        {% endif %}
                        {% if perms.school_major_view %}
                            <li class="{% nav_active request.path 'majorlist' %}">
                                <a href="{% url 'school:majorlist' %}"><i class="fa fa-circle-o"></i>专业</a></li>
                        {% endif %}
                        {% if perms.school_department_view %}
                            <li class="{% nav_active request.path 'departmentlist' %}">
                                <a href="{% url 'school:departmentlist' %}"><i class="fa fa-circle-o"></i>系部</a></li>
                        {% endif %}
                        {% if perms.school_administration_view %}
                            <li class="{% nav_active request.path 'administrationlist' %}">
                                <a href="{% url 'school:administrationlist' %}"><i class="fa fa-circle-o"></i>行政部</a>
                            </li>
                        {% endif %}
                        {% if perms.school_classroom_view %}
                            <li class="{% nav_active request.path 'classroomlist' %}">
                                <a href="{% url 'school:classroomlist' %}"><i class="fa fa-circle-o"></i>教室</a></li>
                        {% endif %}
                        {% if perms.school_schoolterm_view %}
                            <li class="{% nav_active request.path 'schoolterm' %}">
                                <a href="{% url 'school:schoolterm' %}"><i class="fa fa-circle-o"></i>学期</a></li>
                        {% endif %}
                        {% if perms.school_classtime_view %}
                            <li class="{% nav_active request.path 'classtime' %}">
                                <a href="{% url 'school:classtime' %}"><i class="fa fa-circle-o"></i>上课时间</a></li>
                        {% endif %}
                    </ul>
                </li>
            {% endif %}
            {% if perms.user %}
                <li class="treeview {% nav_menu_active request.path 'user' %}">
                    <a href="#"><i class="fa fa-users"></i> <span>用户</span>
                        <i class="fa fa-angle-left pull-right"></i></a>
                    <ul class="treeview-menu">
                        <li class="{% nav_active request.path 'role' %}"><a href="{% url "user:role" %}">
                            <i class="fa fa-circle-o"></i>角色</a></li>
                        {% if perms.user_addpermission %}
                            <li class="{% nav_active request.path 'addpermission' %}">
                                <a href="{% url "user:addpermission" %}"><i class="fa fa-circle-o"></i>权限</a></li>
                        {% endif %}
                    </ul>
                </li>
            {% endif %}
        </ul>
        <!-- /.sidebar-menu -->
    </section>
    <!-- /.sidebar -->
</aside>