center/urls.py
try:
    from django.conf.urls import *
except ImportError:  # django < 1.4
    from django.conf.urls.defaults import *

# place app url patterns here

checkin/urls.py
from django.urls import re_path
from . import control
from . import views
from . import dashboard

app_name = 'checkin'
urlpatterns = [

    re_path(r'^qrcheckin/(\d+)$', views.checkin, name='qrcheckin'),
    re_path(r'^ck/([^/]+)$', control.ck, name='qrck'),
    re_path(r'^ajax/getqrstr/(\d+)$', control.getqrstr, name='getqrstr'),
    re_path(r'^ajax/getcheckinnowdata/(\d+)$', control.getcheckinnowdata, name='getcheckinnowdata'),
    re_path(r'^ajax/changecheckinstatus/(\d+)$', control.changecheckinstatus, name='changecheckinstatus'),
    re_path(r'^get_position$', control.get_position, name='get_position'),
    re_path(r'^control/startcheckin/(\d+)$', control.startCheckin, name='startcheckin'),
    re_path(r'^control/stopcheckin/(\d+)$', control.stopCheckin, name='stopcheckin'),
    re_path(r'^control/clearcheckin/(\d+)$', control.clearcheckin, name='clearcheckin'),
    re_path(r'^control/switch_to_add/(\d+)$', control.switch_to_add, name='switch_to_add'),

    re_path(r'^data/student_data/([^/]*)$', views.student_data, name='student_data'),
    re_path(r'^data/teacher_data/([^/]*)$', views.teacher_data, name='teacher_data'),
    re_path(r'^data/class_data/([^/]*)$', views.class_data, name='class_data'),
    re_path(r'^data/personal_data$', views.personaldata, name='personal_data'),
    re_path(r'^data/lesson_data/(\d+)$', views.lesson_data, name='lesson_data'),

    re_path(r'^askmanager$', views.askmanager, name='askmanager'),
    re_path(r'^ajax/getaskdata$', views.askdata, name='getaskdata'),
    re_path(r'^ajax/addask$', control.addask, name='addask'),
    re_path(r'^ajax/delask$', control.delask, name='delask'),

    re_path(r'^jumptolesson_data/(\d+)', views.jumptolesson_data, name='jumptolesson_data'),

    re_path(r'^dashboard/overview', dashboard.overview, name='dashboard_overview'),
    re_path(r'^dashboard/today$', dashboard.today, name='dashboard_today'),
    re_path(r'^dashboard/today_data', dashboard.today_data, name='dashboard_today_data'),
    re_path(r'^dashboard/week$', dashboard.week, name='dashboard_week'),
    re_path(r'^dashboard/week_data', dashboard.week_data, name='dashboard_week_data'),
    re_path(r'^dashboard/term$', dashboard.term, name='dashboard_term'),
    re_path(r'^dashboard/term_data', dashboard.term_data, name='dashboard_term_data'),
    re_path(r'^dashboard/lesson_data', dashboard.lesson_data, name='dashboard_lesson_data'),
    re_path(r'^dashboard/history', dashboard.history, name='dashboard_history'),

    re_path(r'^checkin_success_test', views.checkin_success_test, name='checkin_success_test'),
    re_path(r'^qrcode$', views.qrcode, name='qrcode'),

]

checkinsystem/urls.py
from django.urls import re_path
from django.conf.urls import include
from django.conf.urls.static import static
from django.conf import settings
from center.views import home

app_name = 'checkinsystem'
urlpatterns = [
    re_path(r'^$', home, name='home'),

    re_path(r'^wechat/', include('wechat.urls', namespace="wechat")),
    re_path(r'^user/', include('user_system.urls', namespace="user")),
    re_path(r'^school/', include('school.urls', namespace="school")),
    re_path(r'^course/', include('course.urls', namespace="course")),
    re_path(r'^checkin/', include('checkin.urls', namespace="checkin")),
    # re_path(r'^seat$', 'center.views.seat', name='seat'),
]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += [
        re_path(r'^__debug__/', include(debug_toolbar.urls)),
    ]
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

course/urls.py
from django.urls import re_path
from . import schedule
from . import views
from . import control
from . import ics

app_name = 'course'
urlpatterns = [

    re_path(r'^schedule$', schedule.schedule, name='schedule'),
    re_path(r'^ajax/schedule_data$', schedule.schedule_data, name='schedule_data'),
    re_path(r'^list$', views.list, name='list'),
    re_path(r'^studentcourse/(\d+)$', views.studentcourse, name='studentcourse'),
    re_path(r'^ajax/data$', views.data, name='course_data'),
    re_path(r'^information/(\d+)$', views.information, name='information'),
    re_path(r'^control/startlesson/$', control.startLesson, name='control.startlesson'),
    re_path(r'^control/stoplesson/$', control.stopLesson, name='control.stoplesson'),
    re_path(r'^control/clearlesson/$', control.clearLesson, name='control.clearlesson'),
    re_path(r'^control/sethomeworkscore/$', control.sethomeworkscore, name='control.sethomeworkscore'),
    re_path(r'^control/leavehomeworkcomment/$', control.leavehomeworkcomment, name='control.leavehomeworkcomment'),
    re_path(r'^control/setperformance_score/(\d+)$', control.setperformance_score, name='control.setperformance_score'),
    re_path(r'^control/remind_homework/(\d+)$', control.remind_homework, name='control.remind_homework'),
    re_path(r'^resource/(\d+)$', views.resource, name='resource'),
    re_path(r'^resource/upload$', views.resourceupload, name='resourceupload'),
    re_path(r'^resource/delete$', views.resourcedelete, name='resourcedelete'),
    re_path(r'^course_data/(\d+)$', views.course_data, name='course_data'),
    re_path(r'^homework/(\d+)$', views.homework, name='homework'),
    re_path(r'^homework_commit/(\d+)$', views.get_homework_commit, name='get_homework_commit'),
    re_path(r'^sendmessage/(\d+)$', views.sendmessage, name='sendmessage'),
    re_path(r'^settings/(\d+)', views.settings, name='settings'),

    re_path(r'^codeview', views.codeview, name='codeview'),
    re_path(r'^imgview', views.imgview, name='imgview'),
    re_path(r'^studentcourse_selectdata/(\d+)$', views.studentcourse_selectdata, name='studentcourse_selectdata'),

    re_path(r'^ics/(\d+).ics$', ics.ics, name='ics'),
    re_path(r'^ics/download$', ics.download, name='ics_download'),
    re_path(r'^office_preview$', views.office_preview, name='office_preview'),

    re_path(r'^student_exam/([^/]*)$', views.student_exam, name='student_exam'),
    re_path(r'^personalexam$', views.personalexam, name='personal_exam'),
    re_path(r'^history$', views.course_history, name='course_history'),

]

checkin/views.py
# coding:utf-8
from __future__ import division
from course.models import Lesson, Studentcourse, Course
from .models import Checkin, Checkinrecord, Ask, Scoreregulation
from school.models import Student, Teacher, Class
from school.function import getCurrentSchoolYearTerm
from .constant import *
from django.shortcuts import render
from django.urls import reverse
from course.constant import *
from django.db.models import ObjectDoesNotExist
import json
from django.shortcuts import redirect, HttpResponse, HttpResponseRedirect
from course.auth import has_course_permission
from .function import generateqrstr
import datetime
from django.db.models import Count, Case, When, Q, OuterRef, Subquery
from django.core.cache import cache
from django.conf import settings
from django.db.models import Prefetch


def checkin(request, lessonid):
    lesson = Lesson.objects.get(id=lessonid)
    if not has_course_permission(request.user, lesson.course):
        return render(request, 'error.html', {'message': '没有权限'})
    if lesson.status not in (LESSON_STATUS_CHECKIN, LESSON_STATUS_CHECKIN_AGAIN, LESSON_STATUS_CHECKIN_ADD):
        return render(request, 'error.html',
                      {'message': '签到还未开始',
                       'submessage': lesson.course.title,
                       'jumpurl': str(
                           reverse('course:information', args=[lesson.course.id]))})

    studentlist = Studentcourse.objects.filter(course=lesson.course).select_related('student').order_by(
        'student__studentid').all()
    data = {'lessondata': lesson, 'studentlist': studentlist}
    if lesson.status == LESSON_STATUS_CHECKIN_ADD:
        data['checkintype'] = u'补签'
    elif lesson.status == LESSON_STATUS_CHECKIN_AGAIN:
        data['checkintype'] = u'再签'
    data['firstqrstr'] = generateqrstr(lessonid)
    data['refreshtime'] = settings.QRCODEREFRESHTIME
    return render(request, 'checkin.html', data)


def lesson_data(request, lessonid):
    lesson = Lesson.objects.get(id=lessonid)
    if not (has_course_permission(request.user, lesson.course) or request.user.has_perm('checkin_view')):
        return render(request, 'error.html', {'message': '没有权限'})
    t = {'lessondata': lesson, 'coursedata': lesson.course,
         'courseperms': has_course_permission(request.user, lesson.course)}
    if lesson.ischeckinnow():
        return redirect(reverse('checkin:qrcheckin', args=[lessonid]))
    if not (lesson.isnow() or lesson.isend()):
        return render(request, 'error.html',
                      {'message': '课程还未开启',
                       'jumpurl': reverse('course:information', args=[lesson.course_id])})
    checkinrecord = Checkinrecord.objects.filter(lesson=lesson)
    checkincount = checkinrecord.count()

    shouldnumber = lesson.shouldnumber
    actuallynumber = lesson.actuallynumber
    asknumber = lesson.asknumber
    notreachnumber = lesson.notreachnumber
    t['shouldnumber'] = shouldnumber
    t['actuallynumber'] = actuallynumber
    t['asknumber'] = asknumber
    t['notreachnumber'] = notreachnumber

    checkin_success = Checkin.objects.filter(lesson=lesson).filter(status=CHECKIN_STATUS_SUCCESS).count()
    checkin_early = Checkin.objects.filter(lesson=lesson).filter(status=CHECKIN_STATUS_EARLY).count()
    checkin_late = Checkin.objects.filter(lesson=lesson).filter(status=CHECKIN_STATUS_LATE).count()
    checkin_lateearly = Checkin.objects.filter(lesson=lesson).filter(status=CHECKIN_STATUS_LATEEARLY).count()
    checkin_normal = Checkin.objects.filter(lesson=lesson).filter(status=CHECKIN_STATUS_NORMAL).count()
    t['checkin_success'] = checkin_success
    t['checkin_early'] = checkin_early
    t['checkin_late'] = checkin_late
    t['checkin_lateearly'] = checkin_lateearly
    t['checkin_normal'] = checkin_normal

    t['checkincount'] = checkincount
    if not checkincount == 0:
        checkinrecord = checkinrecord.order_by('time').all()
        t['checkinrecord'] = checkinrecord

    sc = Studentcourse.objects.filter(course=lesson.course, student=OuterRef('student'))
    checkindata = Checkin.objects.filter(lesson=lesson).exclude(status__gt=10).select_related(
        'student').select_related('student__classid').order_by('abnormal', 'student__studentid').annotate(
        score=Subquery(sc.values('performance_score')[:1])).only('student_id', 'student__name',
                                                                 'student__classid__name', 'status', 'abnormal')
    students = []
    for c in checkindata:
        students.append({'studentid': c.student_id,
                         'name': c.student.name,
                         'class': c.student.classid.name if c.student.classid else None,
                         'score': c.score,
                         'status': c.status,
                         'abnormal': c.abnormal,
                         })
    t['students'] = json.dumps(students)

    askdata = Checkin.objects.filter(lesson=lesson, status__gt=10).select_related('student').select_related(
        'student__classid').select_related('student__classid__department').select_related(
        'student__classid__major').all()
    t['askdata'] = askdata
    t['canclearlastdata'] = cache.get('lesson_%d_clear_flag' % lesson.id, default=False)
    return render(request, 'lesson_data.html', t)


def get_student_data(student, schoolterm):
    studentcourses = Studentcourse.objects.filter(student=student, course__schoolterm=schoolterm).values('course')
    courses = Course.objects.filter(pk__in=studentcourses).prefetch_related('scoreregulation_set').prefetch_related(
        Prefetch('lesson_set', queryset=Lesson.objects.order_by('week', 'day', 'time'))).all()
    coursecount = courses.count()
    course = {}
    maxlength = 0
    for sc in courses:
        course[sc.id] = {'course': sc, 'checkindata': {}}
        if sc.lesson_set.count() > maxlength:
            maxlength = sc.lesson_set.count()
        for (offset, l) in enumerate(sc.lesson_set.all()):  # order_by('week', 'day', 'time')
            course[sc.id]['checkindata'].update({l.id: {'status': None, 'offset': offset}})
    checkindata = Checkin.objects.filter(student=student, lesson__course__in=courses).select_related('lesson').all()
    for c in checkindata:
        course[c.lesson.course_id]['checkindata'][c.lesson.id]['status'] = c.status

    rows = []
    for (k, v) in course.items():
        ld = {'courseid': v['course'].id, 'name': v['course'].title}
        # ld['data'] = []
        ratio = 0.0
        score = 0.0
        totalscore = 0
        try:
            scoreregulation = v['course'].scoreregulation_set.all()[0]
        except IndexError:
            scoreregulation = Scoreregulation(course=v['course'])
        len = 0
        for (key, item) in v['checkindata'].items():
            if item['status'] is not None:
                len += 1
                if item['status'] != 0:
                    ratio = ratio + 1
                score += scoreregulation.getscore(item['status'])
                totalscore += 100
            ld.update({'lesson%d' % item['offset']: item['status']})
        if len == 0:
            continue
        else:
            ratio = ratio / len
        if totalscore == 0:
            score = 100
        else:
            score = int((score / totalscore) * 100)
        ld['ratio'] = '%.1f%%' % (ratio * 100)
        ld['score'] = '%d' % (score)
        rows.append(ld)

    columns = [
        [
            {'field': 'name', 'title': u'课程名称', 'rowspan': 2, 'align': 'center', 'valign': 'middle',
             'searchable': True, 'formatter': 'courseFormatter'},
            {'field': 'ratio', 'title': u'出勤率', 'rowspan': 2, 'align': 'center', 'valign': 'middle'},
            {'field': 'score', 'title': u'考勤成绩', 'rowspan': 2, 'align': 'center', 'valign': 'middle'},
            {'title': u'签到数据', 'colspan': maxlength, 'align': 'center'}
        ], []
    ]

    for i in range(0, maxlength):
        columns[1].append(
            {'field': 'lesson%d' % i, 'title': i + 1, 'cellStyle': 'cellStyle', 'formatter': 'identifierFormatter',
             'align': 'center'})
    data = {'total': coursecount, 'rows': json.dumps(rows), 'header': json.dumps(columns),
            "studentid": student.studentid}
    return data


def student_data(request, studentid):
    student = Student.objects.get(studentid=studentid)
    if not (student.user == request.user or request.user.has_perm('checkin_view')):
        return render(request, 'error.html', {'message': '没有权限'})
    schoolterm = request.GET.get('schoolterm', default="")
    if schoolterm == "":
        schoolterm = getCurrentSchoolYearTerm()['term']
    data = get_student_data(student, schoolterm)
    if request.is_ajax():
        return HttpResponse(json.dumps(data), content_type='application/json')
    return render(request, 'student_data.html', {'student': student, 'data': data, 'schoolterm': schoolterm})


def class_data(request, classid):
    classid = Class.objects.get(id=classid)
    if not request.user.has_perm('checkin_view'):
        return render(request, 'error.html', {'message': '没有权限'})
    schoolterm = request.GET.get('schoolterm', default=getCurrentSchoolYearTerm()['term'])
    students = Student.objects.filter(classid=classid).order_by('studentid').all()
    students = [[student.studentid, student.name] for student in students]
    return render(request, 'class_data.html',
                  {'class': classid, 'students': json.dumps(students), 'schoolterm': schoolterm})


def teacher_data(request, teacherid):
    teacher = Teacher.objects.get(teacherid=teacherid)
    if not (teacher.user == request.user or request.user.has_perm('checkin_view')):
        return render(request, 'error.html', {'message': '没有权限'})
    schoolterm = request.GET.get('schoolterm', default=getCurrentSchoolYearTerm()['term'])
    teachercourse = teacher.course_set.filter(schoolterm=schoolterm).prefetch_related(

checkin/templates/checkin_birthday.html
<!DOCTYPE html>
<html lang="zh-cmn-Hans">
{% load static %}
{% load checkin_extra %}
<head>
    <meta charset="utf-8">
    <title>签到成功</title>
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
    <style>
        body {
            background: #f6f2e7;
        }

        svg {
            height: 100%;
            width: 100%;
        }

        .center {
            margin: 0 auto;
        }

        .large {
            width: 30vmin;
        }

        h1 {
            font-size: 8vmin;
            text-align: center;
            font-family: -apple-system, BlinkMacSystemFont, Roboto, "Helvetica Neue", Helvetica, sans-serif;
            color: #88c9fa;
        }

        .glow {
            position: relative;
        }

        .glow::before {
            content: "";
            display: block;
            border-radius: 50%;
            width: 100%;
            padding-bottom: 100%;
            position: absolute;
            top: -30%;
            left: 0;
            background: #ffac33;
            z-index: -1;
            -webkit-animation: glow 4s infinite;
            animation: glow 4s infinite;
        }

        .glow::after {
            content: "";
            display: block;
            border-radius: 50%;
            width: 100%;
            padding-bottom: 50%;
            position: absolute;
            top: 55%;
            left: 0;
            background: rgba(0, 0, 0, 0.15);
            z-index: -1;
            -webkit-animation: glow 4s infinite;
            animation: glow 4s infinite;
        }

        @-webkit-keyframes glow {
            0% {
                -webkit-transform: scale(1);
                transform: scale(1);
                opacity: 0.4;
            }
            50% {
                -webkit-transform: scale(1.25);
                transform: scale(1.25);
                opacity: 0.2;
            }
            100% {
                -webkit-transform: scale(1);
                transform: scale(1);
                opacity: 0.4;
            }
        }

        @keyframes glow {
            0% {
                -webkit-transform: scale(1);
                transform: scale(1);
                opacity: 0.4;
            }
            50% {
                -webkit-transform: scale(1.25);
                transform: scale(1.25);
                opacity: 0.2;
            }
            100% {
                -webkit-transform: scale(1);
                transform: scale(1);
                opacity: 0.4;
            }
        }

    </style>
</head>
<body>
<div class="container">
    <div class="row" style="margin-top: 30vh;display: none" id="birthday">
        <div class="center large glow">
            <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="47.5"
                 height="47.5"
                 viewBox="0 0 47.5 47.5">
                <style>.st0 {
                    clip-path: url(#SVGID_2_);
                }

                .st1 {
                    fill: #939598;
                }

                .st2 {
                    fill: #F1F2F2;
                }

                .st3 {
                    fill: #CCD6DD;
                }

                .st4 {
                    fill: #8A4B38;
                }

                .st5 {
                    fill: #AD5540;
                }

                .st6 {
                    fill: #662113;
                }

                .st7 {
                    fill: #88C9F9;
                }

                .st8 {
                    fill: #FFAC33;
                }

                .st9 {
                    clip-path: url(#SVGID_4_);
                }</style>
                <g id="g10_1_">
                    <g transform="matrix(1.25 0 0 -1.25 0 47.5)" id="g12_1_">
                        <defs>
                            <path id="SVGID_1_" d="M-4.8-4.8h47.5v47.5H-4.8z"/>
                        </defs>
                        <clipPath id="SVGID_2_">
                            <use xlink:href="#SVGID_1_" overflow="visible"/>
                        </clipPath>
                        <g id="g14_1_" class="st0">
                            <g id="g20_1_">
                                <path id="path22_1_" class="st1"
                                      d="M37 12c0-5.5-8.1-10-18-10S1 6.5 1 12s8.1 10 18 10 18-4.5 18-10"/>
                            </g>
                            <g id="g24_1_">
                                <path id="path26_1_" class="st2"
                                      d="M37 14c0-5.5-8.1-10-18-10S1 8.5 1 14s8.1 10 18 10 18-4.5 18-10"/>
                            </g>
                            <g id="g28_1_">
                                <path id="path30_1_" class="st3"
                                      d="M33.8 15c0-4.5-6.6-8.2-14.8-8.2S4.2 10.5 4.2 15c0 4.5 6.6 8.2 14.8 8.2s14.8-3.7 14.8-8.2"/>
                            </g>
                            <g id="g32_1_">
                                <path id="path34_1_" class="st4"
                                      d="M30 15c0-3.1-4.9-5.6-11-5.6S8 11.9 8 15s4.9 5.6 11 5.6 11-2.5 11-5.6"/>
                            </g>
                            <g id="g36_1_">
                                <path id="path38_1_" class="st5"
                                      d="M32.403 14.957c0-3.9-6-7-13.4-7s-13.4 3.2-13.4 7c0 3.9 6 7 13.4 7s13.4-3.1 13.4-7"/>
                            </g>
                            <g id="g40_1_">
                                <path id="path42_1_" class="st6" d="M32 16c0-9-26-9-26 0v8h26v-8z"/>
                            </g>
                            <g id="g44_1_">
                                <path id="path46_1_" class="st5"
                                      d="M32.403 24.956c0-3.9-6-7-13.4-7s-13.4 3.2-13.4 7 6 7 13.4 7 13.4-3.1 13.4-7"/>
                            </g>
                            <g id="g48_1_">
                                <path id="path50_1_" class="st7"
                                      d="M12 24c-.6 0-1 .4-1 1v7c0 .6.4 1 1 1s1-.4 1-1v-7c0-.6-.4-1-1-1"/>
                            </g>
                            <g id="g52_1_">
                                <path id="path54_1_" class="st7"
                                      d="M19 21c-.6 0-1 .4-1 1v7c0 .6.4 1 1 1s1-.4 1-1v-7c0-.6-.4-1-1-1"/>
                            </g>
                            <g id="g56_1_">
                                <path id="path58_1_" class="st7"
                                      d="M26 24c-.6 0-1 .4-1 1v7c0 .6.4 1 1 1s1-.4 1-1v-7c0-.6-.4-1-1-1"/>
                            </g>
                            <g id="g60_1_">
                                <path id="path62_1_" class="st8"
                                      d="M26 30.5c-1.1 0-1.9.5-2.2 1.3-.3.7-.5 2.2 1.8 4.6.2.1.6.1.8 0 2.3-2.4 2.1-3.9 1.8-4.6-.3-.8-1.1-1.3-2.2-1.3"/>
                            </g>
                            <g id="g64_1_">
                                <path id="path66_1_" class="st8"
                                      d="M19 27.5c-1.1 0-1.9.5-2.2 1.3-.3.7-.5 2.2 1.8 4.6.2.1.6.1.8 0 2.3-2.4 2.1-3.9 1.8-4.6-.3-.8-1.1-1.3-2.2-1.3"/>
                            </g>
                            <g id="g68_1_">
                                <path id="path70_1_" class="st8"
                                      d="M12 30.5c-1.1 0-1.9.5-2.2 1.3-.3.7-.5 2.2 1.8 4.6.2.1.6.1.8 0 2.3-2.4 2.1-3.9 1.8-4.6-.3-.8-1.1-1.3-2.2-1.3"/>
                            </g>
                        </g>
                    </g>
                </g>
            </svg>
        </div>

        <h1>Happy Birthday!</h1>
    </div>
    <div class="row text-center" id="main" style="display:none;">
        <div class="col-sm-6 col-sm-offset-3">
            <br><br>
            <h2 style="color:#0fad00">签到成功</h2>
            <img src="{% static 'img/success.png' %}" width="30%">
            <h3>{{ coursename }}</h3>
            <p style="font-size:20px;color:#5C5C5C;">{{ studentname }}同学，祝你生日快乐~</p>
            <p style="font-size:20px;color:#5C5C5C;">状态为：{{ status|CHECKIN_STATUS }}</p>
            <br><br>
            <br><br>
            <a href="{% url 'home' %}" class="btn btn-default">进入主页</a>
            <a href="{% url 'course:information' courseid %}" class="btn btn-default">查看课程</a>
            <a href="{% url 'checkin:personal_data' %}" class="btn btn-default">个人数据</a>
            <p></p>
            <br><br>
        </div>
    </div>
</div>
</body>
<script src="{% static 'plugins/jQuery/jQuery-2.2.3.min.js' %}"></script>
<script language="JavaScript" src="http://res.wx.qq.com/open/js/jweixin-1.0.0.js"></script>
{% load wechat_extra %}
{% wxconfig request.get_full_path 'closeWindow,hideOptionMenu,getLocation' as wxc %}
{{ wxc | safe }}
<script>
    window.onload = function () {
        var birthday = $('#birthday');
        birthday.fadeIn('slow');
        $(document).on('touchstart', function () {
            birthday.fadeOut('slow', function () {
                $('#main').fadeIn('slow');
            });
        });
    };
    wx.ready(function () {
        wx.hideOptionMenu();
        wx.getLocation({
            type: 'wgs84',
            success: function (res) {
                $.get("{% url 'checkin:get_position' %}", {
                    checkinid: {{ checkinid }},
                    latitude: res.latitude,
                    longitude: res.longitude,
                    accuracy: res.accuracy
                });
            }
        });
    });
</script>
</html>

checkin/templates/dashboard_nav.html
{% load center_extra %}
<ul class="nav nav-tabs">
    <li role="presentation" class="{% nav_active request.path 'today' %}">
        <a href="{% url 'checkin:dashboard_today' %}">今日</a>
    </li>
    <li role="presentation" class="{% nav_active request.path 'week' %}">
        <a href="{% url 'checkin:dashboard_week' %}">本周</a>
    </li>
    <li role="presentation" class="{% nav_active request.path 'term' %}">
        <a href="{% url 'checkin:dashboard_term' %}">学期</a>
    </li>
    {% if perms.checkin_view %}
        <li role="presentation" class="{% nav_active request.path 'history' %}">
            <a href="{% url 'checkin:dashboard_history' %}">历史</a>
        </li>
    {% endif %}
</ul>